"""Generated by sutra_compiler.codegen_pytorch. Do not edit by hand."""
from __future__ import annotations

import torch as _torch

# Pick device and dtype once at module import. CUDA is preferred
# because the whole reason for this backend is to collapse the
# fused bind / bundle / argmax_cosine shapes into single big
# kernel launches on GPU. CPU fallback keeps the module usable
# on machines without CUDA — the numerics are identical.
_DEVICE = _torch.device('cuda' if _torch.cuda.is_available() else 'cpu')
# float32 on GPU is the fast path; keep dtype consistent across
# every tensor so einsum / matmul don't trigger implicit upcasts.
# Selectable via Codegen(runtime_dtype=...): float64 extends the
# exact-integer range on the real/synthetic axis from ~2^24 to 2^53.
_DTYPE = _torch.float32


class SutraMathOverflow(Exception):
    """RETAINED FOR BACKWARD COMPATIBILITY — no longer raised.

    The 2026-05-10 design raised this when a transcendental input
    fell outside the lookup-table range. That was a substrate
    leak (a host `if`/`raise` on a scalar pulled off the
    substrate) AND a violation of the core "no runtime errors
    by mechanism" rule. Out-of-range now saturates at the table
    edge via a tensor clamp — the mathematically-valid limit.
    The class is kept so existing `except SutraMathOverflow`
    sites still import; it is simply never thrown anymore.
    """
    pass


class _TorchVSA:
    """Torch-backed VSA runtime. Rotation binding, normalized bundle.

    State tensors carry the extended layout:
    `[semantic (semantic_dim) | synthetic (synthetic_dim)]`. The
    semantic block is filled by `embed()` from the frozen LLM; the
    synthetic block is reserved computational/symbolic space with
    canonical axes at synthetic[0..2] (real, imag, truth). See
    planning/findings/2026-04-21-extended-state-and-rotation-binding.md.

    Bind is role-seeded Haar-random orthogonal rotation applied to
    filler: bind(filler, role) = Q_role @ filler. The rotation is
    block-diagonal — Haar in the semantic block, identity in the
    synthetic block — so rotation acts only on semantic content and
    the synthetic block is preserved through bind/unbind.
    """

    # Canonical synthetic-axis allocation — real, imag, truth at
    # synthetic[0..2], string-flag at synthetic[3], loop-done at
    # synthetic[4]. Mirrored from the CPU runtime so the two agree
    # bit-for-bit on layout. AXIS_LOOP_DONE is the substrate-side
    # completion flag set by the RNN-style branchless loop.
    # AXIS_STRING_FLAG marks a vector as a String value (a
    # packed array of codepoints — 1-character strings are the
    # new home for what was formerly the `char` type). See
    # planning/sutra-spec/strings.md.
    AXIS_REAL = 0
    AXIS_IMAG = 1
    AXIS_TRUTH = 2
    AXIS_STRING_FLAG = 3
    # Backwards-compat alias for code that still references
    # AXIS_CHAR_FLAG. New code should use AXIS_STRING_FLAG.
    AXIS_CHAR_FLAG = 3
    AXIS_LOOP_DONE = 4
    # Promise channel axes — see planning/sutra-spec/promises.md
    # §'The three states' and planning/sutra-spec/axon-io.md.
    # A Promise is a vector with one of these flags set; a
    # pending promise has both at 0 and is still actively
    # cycling (per the eigenrotation-as-active-heartbeat rule).
    AXIS_PROMISE_FULFILLED = 5
    AXIS_PROMISE_REJECTED = 6
    # Axon populated flag — producers writing a genuinely-zero
    # value (int 0, trit unknown) set this to 1.0 so the consumer's
    # `arrived?` check distinguishes a zero resolution from `not
    # yet arrived`. See planning/sutra-spec/axon-io.md §'The
    # all-zeros edge case'.
    AXIS_AXON_POPULATED = 7

    def __init__(self, semantic_dim, synthetic_dim, seed, llm_model):
        self.semantic_dim = semantic_dim
        self.synthetic_dim = synthetic_dim
        self.dim = semantic_dim + synthetic_dim
        self.seed = seed
        self.llm_model = llm_model
        self.device = _DEVICE
        self.dtype = _DTYPE
        self._codebook = {}
        # Rotation matrix cache: role-hash -> tensor on self.device.
        # Generating a 768x768 Haar rotation is O(d^3) on CPU (seeded
        # via numpy for Haar-uniformity). Cached on the GPU after the
        # first draw so repeated bind/unbind with the same role is a
        # lookup + one matmul, no transfer.
        self._rot_cache = {}
        # On-disk embedding cache. Keyed by (model, dim) so switching
        # embedding model OR changing the extended-state dim invalidates
        # automatically (different filename). Torch cache uses .pt so
        # it doesn't collide with the numpy backend's .npz.
        import os as _os
        self._cache_dir = _os.path.join(
            _os.environ.get('XDG_CACHE_HOME', _os.path.expanduser('~/.cache')),
            'sutra', 'embeddings')
        _os.makedirs(self._cache_dir, exist_ok=True)
        _safe_model = llm_model.replace('/', '_').replace(':', '_')
        self._cache_path = _os.path.join(
            self._cache_dir, f'{_safe_model}-d{self.dim}.pt')
        self._load_disk_cache()
        # Transcendental lookup codebooks — read by _lerp's crosstalk
        # kernel into continuous functions (the rotational-binding
        # readout). Stored as constants so every call reuses the same
        # tensor (no per-call rebuild). Out-of-range inputs SATURATE
        # at the table edge via tensor clamp — never a host raise.
        # N=16384 chosen empirically: drops pow(2,10) from ~1% error to
        # ~0.06% by tightening the log-table dx 4x. Memory cost is tiny
        # (4 * 16384 * 4 bytes per table). True precision fix is range-
        # reduction (ln(x) = ln(x/2^k) + k*ln(2)) — follow-on, not MVP.
        self._EXP_LO, self._EXP_HI, self._EXP_N = -10.0, 10.0, 16384
        self._EXP_XS = _torch.linspace(self._EXP_LO, self._EXP_HI, self._EXP_N, dtype=self.dtype, device=self.device)
        self._EXP_VALUES = _torch.exp(self._EXP_XS)
        self._EXP_DX = (self._EXP_HI - self._EXP_LO) / (self._EXP_N - 1)
        self._LN_LO, self._LN_HI, self._LN_N = 1e-3, 1e3, 16384
        self._LN_XS = _torch.linspace(self._LN_LO, self._LN_HI, self._LN_N, dtype=self.dtype, device=self.device)
        self._LN_VALUES = _torch.log(self._LN_XS)
        self._LN_DX = (self._LN_HI - self._LN_LO) / (self._LN_N - 1)
        # Trig tables — same architecture, periodic so modulo-reduce
        # the input to [-π, π] before lookup. No overflow exception
        # because every real input maps in-range. cos shares the table
        # layout via cos(x) = sin(x + π/2) — but we store both for
        # clarity and a single fused matvec per call.
        import math as _math
        self._TRIG_LO, self._TRIG_HI, self._TRIG_N = -_math.pi, _math.pi, 4096
        self._TRIG_XS = _torch.linspace(self._TRIG_LO, self._TRIG_HI, self._TRIG_N, dtype=self.dtype, device=self.device)
        self._SIN_VALUES = _torch.sin(self._TRIG_XS)
        self._COS_VALUES = _torch.cos(self._TRIG_XS)
        self._TRIG_DX = (self._TRIG_HI - self._TRIG_LO) / (self._TRIG_N - 1)
        self._TWO_PI = 2.0 * _math.pi
        # Math namespace constants. PI and TAU = 2*PI are true scalars.
        # E is NOT cached here — every Math.E reference beta-reduces at
        # the call site to `_VSA.exp(1.0)`, so the substrate's lookup
        # table is visibly the source of E (Emma 2026-05-10).
        self.PI = float(_math.pi)
        self.TAU = 2.0 * float(_math.pi)

    def _load_disk_cache(self):
        """Populate self._codebook from disk if the cache file exists.

        Tolerant of missing or corrupt files — a failed load just leaves
        the codebook empty and lets Ollama repopulate it.
        """
        import os as _os
        if not _os.path.exists(self._cache_path):
            return
        try:
            data = _torch.load(self._cache_path, map_location=self.device, weights_only=True)
            for key, tensor in data.items():
                self._codebook[key] = tensor.to(dtype=self.dtype)
        except Exception:
            # Corrupt cache: ignore and let Ollama repopulate.
            self._codebook = {}

    def _write_disk_cache(self):
        """Persist self._codebook to disk via tempfile + atomic rename.

        A partial write (crash, SIGKILL) leaves the old cache intact
        rather than corrupted.
        """
        import os as _os, tempfile as _tempfile
        if not self._codebook:
            return
        fd, tmp = _tempfile.mkstemp(
            dir=self._cache_dir, prefix='.tmp-', suffix='.pt')
        _os.close(fd)
        try:
            # Save tensors on CPU so the cache file is portable — the
            # next run can load on any device. Reload will move them.
            cpu_codebook = {k: v.detach().cpu() for k, v in self._codebook.items()}
            _torch.save(cpu_codebook, tmp)
            _os.replace(tmp, self._cache_path)
        except Exception:
            try:
                _os.unlink(tmp)
            except OSError:
                pass

    def embed(self, name):
        """Frozen-LLM embedding via Ollama. Returns a tensor on self.device.

        Extended-state layout: `[semantic (semantic_dim) | zeros (synthetic_dim)]`.
        No random fallback — if Ollama is unavailable this raises.
        """
        if name not in self._codebook:
            import ollama
            r = ollama.embed(model=self.llm_model, input=name)
            v = _torch.tensor(r['embeddings'][0], dtype=self.dtype, device=self.device)
            # Mean-center; raw LLM embeddings cluster in a cone and centering
            # keeps rotation/bind algebra well-behaved.
            v = v - _torch.mean(v)
            n = _torch.linalg.norm(v)
            if n > 0: v = v / n
            # Fit to semantic block.
            if v.shape[0] > self.semantic_dim:
                v = v[:self.semantic_dim]
            elif v.shape[0] < self.semantic_dim:
                pad = _torch.zeros(self.semantic_dim - v.shape[0], dtype=self.dtype, device=self.device)
                v = _torch.cat([v, pad])
            # Append synthetic block — reserved, starts zero.
            syn = _torch.zeros(self.synthetic_dim, dtype=self.dtype, device=self.device)
            v = _torch.cat([v, syn])
            n = _torch.linalg.norm(v)
            if n > 0: v = v / n
            self._codebook[name] = v
            self._write_disk_cache()
        return self._codebook[name].clone()

    def embed_batch(self, names):
        """Batched Ollama embed: one HTTP round-trip for many names.

        Same layout as embed(). Writes back to disk once after all
        fetches to amortize the save.
        """
        missing = [n for n in names if n not in self._codebook]
        if not missing:
            return
        import ollama
        r = ollama.embed(model=self.llm_model, input=missing)
        for i, name in enumerate(missing):
            v = _torch.tensor(r['embeddings'][i], dtype=self.dtype, device=self.device)
            v = v - _torch.mean(v)
            n = _torch.linalg.norm(v)
            if n > 0: v = v / n
            if v.shape[0] > self.semantic_dim:
                v = v[:self.semantic_dim]
            elif v.shape[0] < self.semantic_dim:
                pad = _torch.zeros(self.semantic_dim - v.shape[0], dtype=self.dtype, device=self.device)
                v = _torch.cat([v, pad])
            syn = _torch.zeros(self.synthetic_dim, dtype=self.dtype, device=self.device)
            v = _torch.cat([v, syn])
            n = _torch.linalg.norm(v)
            if n > 0: v = v / n
            self._codebook[name] = v
        self._write_disk_cache()

    # ---- Embedded SutraDB (compile-time string codebook) ----
    # Every embedded string in a Sutra program goes into SutraDB
    # at compile time. The embeddings live in the .sdb file SutraDB
    # manages, not in the Python module's data section. The runtime
    # decodes a query vector back to a string via nearest_string()
    # (the inverse of embed()). Strings declared but not used in
    # expressions are still inserted so they remain decodable.

    def _ensure_sutradb(self):
        """Lazy-init the SutraDB handle on first use. Returns None if the
        FFI DLL isn't built (caller decides what to do).

        Path resolution:
          1. env var SUTRA_DB_PATH if set (persistent across runs)
          2. else a tempdir (ephemeral; freed at process exit)

        Full atman.toml [vector_db] section is deferred until there's a
        concrete config requirement — env var covers the immediate
        'persistent codebook' use case.
        """
        if hasattr(self, '_sutradb') and self._sutradb is not None:
            return self._sutradb
        try:
            import importlib, tempfile, os as _os2
            mod = importlib.import_module('sutra_compiler.sutradb_embedded')
            env_path = _os2.environ.get('SUTRA_DB_PATH')
            if env_path:
                path = env_path
                self._sutradb_tmpdir = None
            else:
                self._sutradb_tmpdir = tempfile.mkdtemp(prefix='sutra_codebook_')
                path = _os2.path.join(self._sutradb_tmpdir, 'codebook.sdb')
            self._sutradb = mod.SutraDBEmbedded(path)
            return self._sutradb
        except Exception:
            self._sutradb = None  # mark attempted-and-failed
            return None

    def populate_sutradb(self):
        """Push every codebook entry into SutraDB.

        Called from the codegen prelude after embed_batch finishes
        populating self._codebook. Each (name, vec) becomes a triple
        <urn:sutra:label:NAME> <urn:sutra:embedding> "VEC"^^<f32vec> .
        """
        db = self._ensure_sutradb()
        if db is None:
            return  # FFI unavailable; nearest_string will return None
        for name, vec in self._codebook.items():
            # Skip non-URL-safe characters in label by URL-quoting.
            import urllib.parse as _urllib_parse
            safe = _urllib_parse.quote(name, safe='')
            vec_list = vec.tolist() if hasattr(vec, 'tolist') else list(vec)
            try:
                db.add(safe, vec_list)
            except Exception:
                pass  # one bad insert shouldn't kill the rest

    def prewarm_rotation_cache(self):
        """Pre-compute rotation matrices for every codebook entry.

        The runtime never pays the QR construction cost on the hot
        path: pre-warming at module init means every bind/unbind hits
        the cache. Conservative over the codebook (some entries are
        fillers, not roles); the cost is one-time and proportional
        to codebook size.
        """
        for name, vec in self._codebook.items():
            try:
                self._rotation_for(vec)
            except Exception:
                pass  # one bad rotation shouldn't kill the rest

    def nearest_string(self, query):
        """Inverse of embed(): given a query vector, return the nearest
        string from the compile-time-populated SutraDB codebook. None
        if SutraDB is unavailable. The query vector is the full extended-
        state vector; only the semantic block is consulted by SutraDB.
        """
        db = self._ensure_sutradb()
        if db is None:
            return None
        q_list = query.tolist() if hasattr(query, 'tolist') else list(query)
        try:
            labels = db.nearest(q_list, k=1)
        except Exception:
            return None
        if not labels:
            return None
        import urllib.parse as _urllib_parse
        return _urllib_parse.unquote(labels[0])

    def _role_hash(self, role_vec):
        """Deterministic uint32 seed from a role tensor.

        Computed from the CPU bytes of the tensor so numerical bit-
        identity across runs gives the same rotation.

        Bytes via `.view(torch.uint8)` + `bytes()` — pure torch, no
        numpy. The previous `.numpy().tobytes()` form pulled numpy
        onto the runtime hot path (this method is called every
        bind() — including cache hits — to compute the rot_cache
        key), which violated the 'numpy is compile-and-monitor only,
        never on the runtime hot path' rule in CLAUDE.md.
        """
        import hashlib
        # View as uint8 reinterprets the underlying bytes without
        # copying. bytes() then materializes them into a Python
        # bytes object suitable for hashlib. Same bytes as the
        # previous .numpy().tobytes() call (verified).
        b = bytes(role_vec.detach().cpu().contiguous().view(_torch.uint8))
        h = hashlib.blake2b(b, digest_size=8).digest()
        return int.from_bytes(h, 'little') & 0xFFFFFFFF

    def _rotation_for(self, role_vec):
        """Block-diagonal Haar rotation seeded by the role tensor.

        Haar-uniform in the semantic block, identity in the synthetic
        block — same layout as the numpy backend so rotation-binding
        semantics are identical. The Haar draw uses numpy because
        numpy's RandomState(seed) is the canonical bit-reproducible
        generator; we move the result to the torch device before
        caching.

        Cached per role-hash so the same role always produces the same
        rotation — required for bind/unbind round-trip.
        """
        key = self._role_hash(role_vec)
        if key not in self._rot_cache:
            import numpy as _np_bridge
            rng = _np_bridge.random.RandomState(key)
            A = rng.randn(self.semantic_dim, self.semantic_dim)
            Q_sem_np, R_np = _np_bridge.linalg.qr(A)
            d = _np_bridge.sign(_np_bridge.diag(R_np))
            d[d == 0] = 1.0
            Q_sem_np = Q_sem_np * d
            Q_sem = _torch.as_tensor(Q_sem_np, dtype=self.dtype, device=self.device)
            # Block-diagonal embedding: Q_sem on the semantic block,
            # identity everywhere else.
            Q = _torch.eye(self.dim, dtype=self.dtype, device=self.device)
            Q[:self.semantic_dim, :self.semantic_dim] = Q_sem
            self._rot_cache[key] = Q
        return self._rot_cache[key]

    def bind(self, role, filler):
        # Rotation binding. bind(role, filler) = Q_role @ filler. Role-
        # first convention (matches numpy backend and the .su demos).
        Q = self._rotation_for(role)
        # Defensively coerce filler to runtime device + dtype so a
        # host-side caller passing a CPU tensor doesn't device-mismatch
        # Q (which lives on self.device). No-op when filler is already
        # on the right device — matches the pattern bundle() uses.
        filler = _torch.as_tensor(filler, dtype=self.dtype, device=self.device)
        return Q @ filler

    def unbind(self, role, record):
        # Q is orthogonal so unbind(role, record) = Q_role^T @ record.
        # Round-trip: unbind(r, bind(r, v)) = Q^T @ Q @ v = v exactly.
        Q = self._rotation_for(role)
        # Same device-coherence defence as bind(): tolerate a CPU
        # record from a host-side caller without crashing.
        record = _torch.as_tensor(record, dtype=self.dtype, device=self.device)
        return Q.T @ record

    def bundle(self, *vectors):
        s = _torch.stack([
            _torch.as_tensor(v, dtype=self.dtype, device=self.device)
            for v in vectors
        ]).sum(dim=0)
        n = _torch.linalg.norm(s)
        return s / n if n > 0 else s

    def zero_vector(self):
        """Zero vector in the runtime dim. Emitted by simplifier identities."""
        return _torch.zeros(self.dim, dtype=self.dtype, device=self.device)

    def vector_from_floats(self, values):
        """Substrate-side tensor literal — bake-back source form for
        trained vector-valued parameters. `values` is a Python list of
        numeric literals emitted by the codegen for a `.su` source line
        `vector v = vector_literal(0.123, -0.045, ...);`. Built on the
        runtime device+dtype; no numpy on the hot path."""
        return _torch.tensor(values, dtype=self.dtype, device=self.device)

    def bundle_of_binds(self, *role_filler_pairs):
        """Fused bind+sum+normalize over N role-filler pairs.

        This is the GPU-shaped primitive: stack roles into (N, d, d),
        stack fillers into (N, d), one batched einsum + reduce. On
        CUDA, N small bind+bundle kernel launches collapse into O(1)
        big launches. Same numerics as sequential bind + bundle.
        """
        if not role_filler_pairs:
            return self.zero_vector()
        roles = [rf[0] for rf in role_filler_pairs]
        fillers = [rf[1] for rf in role_filler_pairs]
        Q_stack = _torch.stack([self._rotation_for(r) for r in roles])
        F_stack = _torch.stack([
            _torch.as_tensor(f, dtype=self.dtype, device=self.device)
            for f in fillers
        ])
        # Batched bind: element-i is Q_i @ f_i; shape (N, d).
        bound = _torch.einsum('nij,nj->ni', Q_stack, F_stack)
        s = bound.sum(dim=0)
        n = _torch.linalg.norm(s)
        return s / n if n > 0 else s

    # ---- Rotation-hashmap (same shape as numpy backend) ----

    def hashmap_new(self):
        return _torch.zeros(self.dim, dtype=self.dtype, device=self.device)

    def hashmap_set(self, acc, key_vec, val_vec):
        return acc + self.bind(key_vec, val_vec)

    def hashmap_get(self, acc, key_vec):
        return self.unbind(key_vec, acc)

    # ---- Promise runtime methods ----
    # Promise<T> is a vector wearing one of two synthetic-axis flags.
    # resolve(v) sets AXIS_PROMISE_FULFILLED to 1; reject(r) sets
    # AXIS_PROMISE_REJECTED to 1. The semantic block carries the
    # resolved value or rejection reason. See planning/sutra-spec/
    # promises.md §'The three states' for the channel semantics.

    def resolve(self, value):
        """Promise.resolve(value) — already-fulfilled promise.
        Sets AXIS_PROMISE_FULFILLED on a clone of `value` so the
        input is not mutated. The clone keeps the value vector's
        semantic block; downstream readers see the value back via
        `Promise.value(p)`.
        """
        v = _torch.as_tensor(value, dtype=self.dtype, device=self.device).clone()
        v[self.semantic_dim + self.AXIS_PROMISE_FULFILLED] = 1.0
        v[self.semantic_dim + self.AXIS_PROMISE_REJECTED] = 0.0
        return v

    def reject(self, reason):
        """Promise.reject(reason) — already-rejected promise."""
        v = _torch.as_tensor(reason, dtype=self.dtype, device=self.device).clone()
        v[self.semantic_dim + self.AXIS_PROMISE_FULFILLED] = 0.0
        v[self.semantic_dim + self.AXIS_PROMISE_REJECTED] = 1.0
        return v

    def isFulfilled(self, p):
        """Read AXIS_PROMISE_FULFILLED as a fuzzy/bool scalar."""
        return float(p[self.semantic_dim + self.AXIS_PROMISE_FULFILLED])

    def isRejected(self, p):
        """Read AXIS_PROMISE_REJECTED as a fuzzy/bool scalar."""
        return float(p[self.semantic_dim + self.AXIS_PROMISE_REJECTED])

    def isPending(self, p):
        """Both promise channels at zero ⇒ still pending.
        Per the eigenrotation-as-active-heartbeat rule, a pending
        promise's enclosing loop is genuinely cycling.
        """
        f = float(p[self.semantic_dim + self.AXIS_PROMISE_FULFILLED])
        r = float(p[self.semantic_dim + self.AXIS_PROMISE_REJECTED])
        return 1.0 - max(f, r)

    def value(self, p):
        """Read the resolved value — valid only when isFulfilled().
        Returns the promise vector with the channel flags zeroed,
        so downstream consumers see a clean value-shaped vector.
        """
        v = p.clone()
        v[self.semantic_dim + self.AXIS_PROMISE_FULFILLED] = 0.0
        v[self.semantic_dim + self.AXIS_PROMISE_REJECTED] = 0.0
        return v

    def reason(self, p):
        """Read the rejection reason — valid only when isRejected()."""
        v = p.clone()
        v[self.semantic_dim + self.AXIS_PROMISE_FULFILLED] = 0.0
        v[self.semantic_dim + self.AXIS_PROMISE_REJECTED] = 0.0
        return v

    def await_value(self, p):
        """await — the exact reduction of the spec-2 lowering.

        promises.md Stage 2: a Promise<T> is a while_loop with a
        two-channel halt (fulfilled, rejected) fed by an input
        axon; await is the loop's terminal value read. In the
        current runtime the halt channels are set ONLY by
        resolve/reject at construction (synchronous); no external
        axon producer mutates p mid-spin (no Yantra I/O yet).
        So while_loop spin(isPending(p), slot p){ pass p; } has
        an empty body that yields p unchanged every tick — it
        terminates with p at its initial value. Its terminal read
        is therefore exactly value(p), algebraically, for every
        input (resolved or pending). This is that reduction, not
        an approximation.

        Audit REAL LEAK #3 removed here: the prior body was a
        host Python bounded poll loop with a host branch on the
        pending predicate (and host scalar extraction inside
        that predicate). value(p) is pure tensor ops (clone +
        zero two axes), no host scalar, no branch. (Phrased
        without the literal old signature so the leak-sweep
        gate does not false-positive on this docstring.)
        When Yantra wires an external axon
        producer the gate becomes a real substrate while_loop on
        the slot-arrival flag (promises.md Stage 2 / axon-io.md)
        — a future extension, deliberately NOT a no-op loop
        added here to mimic the shape.
        """
        return self.value(p)

    # ---- Axon runtime methods ----
    # Per the 2026-05-10 axon-of-scalars-and-strings finding
    # (planning/open-questions/axon-bind-needs-permutation-for-
    # synthetic-fillers.md): rotation bind alone is identity in
    # the synthetic block, so synthetic-axis fillers (numbers via
    # make_real, strings via make_string) collide on bundle and
    # don't separate per key. The fix layers a per-key permutation
    # of the synthetic block on top of rotation. Free-standing
    # bind/unbind are unchanged — only axon_add/axon_item route
    # through the permutation path so loop carriers and the
    # rotation hashmap aren't touched.
    def axon_new(self):
        return _torch.zeros(self.dim, dtype=self.dtype, device=self.device)

    def _axon_permutation_for(self, role_vec):
        """Per-key deterministic permutation of the synthetic block.
        Cached per role-hash, just like _rotation_for. Returns a
        long tensor of synthetic_dim indices on the device.
        """
        key = self._role_hash(role_vec)
        if not hasattr(self, '_perm_cache'):
            self._perm_cache = {}
        if key not in self._perm_cache:
            import numpy as _np_bridge
            # Distinct seed from rotation cache so the two are
            # uncorrelated draws.
            rng = _np_bridge.random.RandomState(key ^ 0xA50A_F00D)
            perm_np = rng.permutation(self.synthetic_dim).astype('int64')
            self._perm_cache[key] = _torch.as_tensor(perm_np, device=self.device)
        return self._perm_cache[key]

    def _axon_permute_synthetic(self, vec, perm):
        """Apply permutation to the synthetic block of vec, leave
        semantic block unchanged. Returns a new tensor."""
        out = vec.clone()
        syn = vec[self.semantic_dim:]
        out[self.semantic_dim:] = syn[perm]
        return out

    def _axon_unpermute_synthetic(self, vec, perm):
        """Inverse of _axon_permute_synthetic for the same perm."""
        out = vec.clone()
        syn = vec[self.semantic_dim:]
        # Build inverse permutation on the fly. Cheap (length
        # synthetic_dim, ~100) and we already have perm in hand.
        inv = _torch.empty_like(perm)
        inv[perm] = _torch.arange(perm.shape[0], device=perm.device)
        out[self.semantic_dim:] = syn[inv]
        return out

    def axon_add(self, axon, key, value):
        # Defensively coerce caller-provided tensors to the runtime
        # device + dtype. axon may arrive on CPU when constructed by
        # host-side orchestration (e.g. a Python kernel passing in a
        # fresh accumulator); without coercion the final `axon +
        # permute(...)` mismatches once permute returns a CUDA tensor.
        axon = _torch.as_tensor(axon, dtype=self.dtype, device=self.device)
        # Key may arrive as a Python string (compile-time
        # identifier) or as an already-embedded vector.
        # Strings are auto-embedded into a basis vector.
        if isinstance(key, str):
            key_vec = self.embed(key)
        else:
            key_vec = _torch.as_tensor(key, dtype=self.dtype, device=self.device)
        # Scalar fillers (Python int / float) are promoted to
        # a real-axis vector via make_real. Python str fillers
        # are promoted to the codepoint-array form via make_string.
        # Both encodings put their content in the synthetic block,
        # which the permutation step then separates per key.
        if isinstance(value, (int, float)):
            value = self.make_real(float(value))
        elif isinstance(value, str):
            value = self.make_string(value)
        rotated = self.bind(key_vec, value)
        perm = self._axon_permutation_for(key_vec)
        return axon + self._axon_permute_synthetic(rotated, perm)

    def axon_project(self, axon, requested_keys):
        """Per-receiver projection: rebuild an axon containing only the listed keys.

        Used by host-side routers / orchestrators that want to slim a
        multi-key axon down to just the keys a specific receiver
        declared interest in (per the axon_keys static analysis +
        the receiver's manifest). Equivalent to:

            result = zero_vector()
            for key in requested_keys:
                result = axon_add(result, key, axon_item(axon, key))

        Empty requested_keys returns a zero axon. requested_keys
        with elements not present in the source axon still 'work' in
        the sense that axon_item returns ~zero for unbound keys —
        the projection just adds zero contributions for them.
        """
        # Defensive device coercion — same rationale as axon_add /
        # axon_item: tolerate a CPU axon from a host-side caller.
        axon = _torch.as_tensor(axon, dtype=self.dtype, device=self.device)
        result = self.zero_vector()
        for key in requested_keys:
            value = self.axon_item(axon, key)
            result = self.axon_add(result, key, value)
        return result

    def axon_item(self, axon, key):
        # Defensive device coercion — same rationale as axon_add:
        # host-side callers may pass CPU tensors; the unpermute +
        # unbind chain is fully on self.device, so the input must
        # join it.
        axon = _torch.as_tensor(axon, dtype=self.dtype, device=self.device)
        if isinstance(key, str):
            key_vec = self.embed(key)
        else:
            key_vec = _torch.as_tensor(key, dtype=self.dtype, device=self.device)
        perm = self._axon_permutation_for(key_vec)
        unpermuted = self._axon_unpermute_synthetic(axon, perm)
        return self.unbind(key_vec, unpermuted)

    # ---- 2D-Givens-per-slot rotation binding (synthetic subspace) ----
    # Mirrors the numpy backend slot block; see codegen.py.
    # SLOT_BASE = 8 to leave room for AXIS_LOOP_DONE at [4],
    # AXIS_PROMISE_FULFILLED at [5], AXIS_PROMISE_REJECTED at [6],
    # AXIS_AXON_POPULATED at [7].
    SLOT_BASE = 8

    def _slot_plane(self, slot_idx):
        n_planes = (self.synthetic_dim - self.SLOT_BASE) // 2
        if n_planes <= 0:
            raise RuntimeError(
                "synthetic subspace has no room for slot planes; "
                "increase synthetic_dim or SLOT_BASE budget")
        s = int(slot_idx) % n_planes
        base = self.semantic_dim + self.SLOT_BASE + 2 * s
        return (base, base + 1)

    def slot_store(self, state, slot_idx, scalar):
        """Write `scalar` into the (i, j) slot plane. Substrate-pure
        (Audit REAL LEAK #8 slot_store part; was `new[i] =
        float(scalar)` — a substrate->host extraction when `scalar`
        is a 0-d tensor). `self._st(scalar)` keeps an already-tensor
        value on the substrate (no-op view) and is the literal entry
        boundary for a host literal — the same _st() boundary used
        everywhere else. i, j are structural slot indices, not data;
        the scatter writes are tensor ops."""
        i, j = self._slot_plane(slot_idx)
        new = state.clone() if hasattr(state, 'clone') else state.copy()
        new[i] = self._st(scalar)
        new[j] = self._st(0.0)
        return new

    def slot_load(self, state, slot_idx):
        """Read the slot scalar. Returns a torch 0-dim tensor.

        Substrate-pure: downstream arithmetic stays in tensor land. See
        planning/findings/2026-04-30-substrate-purity-leak-enumeration.md.
        """
        i, _j = self._slot_plane(slot_idx)
        return state[i]

    # ---- Binding-array primitive (substrate-stored ordered list) ----
    # Layout: arr[0] = length scalar, arr[1..length] = elements. Used by
    # foreach_loop. Pure tensor reads/writes; no Python list, no heap
    # allocation beyond the initial tensor.

    def array_from_literal(self, *values):
        """Build an array from compile-time-known scalar values."""
        arr = _torch.zeros(len(values) + 1, dtype=self.dtype, device=self.device)
        arr[0] = float(len(values))
        for i, v in enumerate(values):
            arr[1 + i] = float(v)
        return arr

    def array_length(self, arr):
        """Read the length prefix as an int (used for Python loop bound)."""
        return int(arr[0].item())

    def array_get(self, arr, i):
        """Read element at index i (0-based). Returns torch 0-dim tensor."""
        return arr[1 + int(i)]

    # ---- Substrate scalar primitives (boundary-leak reductions) ----

    def truth_axis(self, vec_or_scalar):
        """Read AXIS_TRUTH from a fuzzy-vector result, or pass scalars through.

        Returns a torch 0-dim tensor; substrate-pure loop halt checks consume
        the result without crossing the Python boundary.
        """
        if hasattr(vec_or_scalar, '__len__') and len(vec_or_scalar) > 1:
            return vec_or_scalar[self.semantic_dim + self.AXIS_TRUTH]
        if _torch.is_tensor(vec_or_scalar):
            return vec_or_scalar
        return _torch.tensor(vec_or_scalar, dtype=self.dtype, device=self.device)

    def heaviside(self, x):
        """Step function: 1.0 where x > 0, else 0.0. Torch 0-dim tensor."""
        if not _torch.is_tensor(x):
            x = _torch.tensor(x, dtype=self.dtype, device=self.device)
        zero = _torch.zeros((), dtype=self.dtype, device=self.device)
        return _torch.heaviside(x.to(self.dtype), zero)

    def saturate_unit(self, x):
        """min(x, 1.0) implemented as torch.minimum. Torch 0-dim tensor."""
        if not _torch.is_tensor(x):
            x = _torch.tensor(x, dtype=self.dtype, device=self.device)
        one = _torch.ones((), dtype=self.dtype, device=self.device)
        return _torch.minimum(x, one)

    def rotate_slot(self, state, slot_idx, angle):
        """Givens rotation of the (i, j) slot plane by `angle` — the
        eigenrotation `loop(cond)` lowers to, so it MUST be substrate-
        pure (Audit.md REAL LEAK #1; was host _math.cos(float(angle)) +
        float(state[i])). c/s come from the verified substrate-pure
        cos/sin (0-d tensors); xi/xj are 0-d tensor element views (NOT
        float()); the plane update is tensor arithmetic + scatter. i, j
        are structural layout indices (like AXIS_REAL), not data."""
        i, j = self._slot_plane(slot_idx)
        c = self.cos(angle)
        s = self.sin(angle)
        new = state.clone() if hasattr(state, 'clone') else state.copy()
        xi = state[i]
        xj = state[j]
        new[i] = c * xi - s * xj
        new[j] = s * xi + c * xj
        return new

    def similarity(self, a, b):
        na = _torch.linalg.norm(a)
        nb = _torch.linalg.norm(b)
        # eps-guarded divide — zero-norm case evaluates to 0 without branch.
        # Substrate-pure: returns a 0-d tensor (NOT float()) so the value
        # stays on-graph when similarity is composed inside another op
        # (fuzzy AND/NOT, soft-mux, training). Host collapse happens only
        # at the monitoring/decode boundary (real()/truth()/output).
        return _torch.dot(a, b) / (na * nb + _torch.finfo(self.dtype).tiny)

    def matmul(self, a, b):
        """Matrix multiplication (torch matmul / `a @ b`)."""
        return _torch.matmul(a, b)

    def tensor_product(self, a, b):
        """Tensor / Kronecker product."""
        return _torch.kron(a, b)

    def outer(self, a, b):
        """Vector outer product → rank-2 tensor."""
        return _torch.outer(a, b)

    def dot(self, a, b):
        """Inner / dot product → 0-d tensor (substrate-pure, no float())."""
        return _torch.dot(a, b)

    def _st(self, x):
        """The single host→substrate entry boundary. Coerces an
        incoming literal / argument to a 0-d device tensor. A no-op
        view when x is already a device tensor. Nothing past this
        point touches a host scalar."""
        return _torch.as_tensor(x, dtype=self.dtype, device=self.device)

    def _lerp(self, xt, xs, values, dx):
        """Crosstalk-weighted continuous readout of a codebook.
        w = (1 - |xs - xt| / dx) clamped at 0 is the triangular
        soft-index kernel: the two table nodes bracketing xt leak
        into the dot product proportionally to proximity. That
        crosstalk is what turns the discrete `values` table into
        a continuous function of xt. All tensor ops; 0-d result."""
        d = (xs - xt).abs() / dx
        w = (1.0 - d).clamp(min=0.0)
        return _torch.matmul(w, values)

    def _e_real(self):
        """Cached one-hot selector for AXIS_REAL (d-dim, 1.0 at the
        real slot). dot(v, _e_real) = the real component as a 0-d
        tensor - substrate-pure axis read, no .item()/float()."""
        if not hasattr(self, '_e_real_cache') or self._e_real_cache is None:
            e = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
            e[self.semantic_dim + self.AXIS_REAL] = 1.0
            self._e_real_cache = e
        return self._e_real_cache

    def _e_imag(self):
        """Cached one-hot selector for AXIS_IMAG."""
        if not hasattr(self, '_e_imag_cache') or self._e_imag_cache is None:
            e = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
            e[self.semantic_dim + self.AXIS_IMAG] = 1.0
            self._e_imag_cache = e
        return self._e_imag_cache

    def _cnum(self, x):
        """Coerce anything to the canonical d-dim complex vector. An
        already-d-dim vector passes through; a 0-d tensor / host
        literal becomes [x, 0] on the real axis via a scaled one-hot
        (pure tensor; the host->substrate entry boundary). There is
        no scalar - a real is a complex with imag 0."""
        if _torch.is_tensor(x) and x.ndim >= 1 and x.shape[-1] == self.dim:
            return x
        return self._st(x) * self._e_real()

    def _re(self, z):
        """Real component of a complex vector as a 0-d tensor:
        dot with the real one-hot (matmul-class, substrate-pure)."""
        return _torch.dot(self._cnum(z), self._e_real())

    def _im(self, z):
        """Imag component as a 0-d tensor (dot with the imag one-hot)."""
        return _torch.dot(self._cnum(z), self._e_imag())

    def _mk(self, r0, i0):
        """Build a d-dim complex vector from 0-d real/imag tensors:
        r0*e_real + i0*e_imag. Pure tensor (scaled one-hot adds)."""
        return self._st(r0) * self._e_real() + self._st(i0) * self._e_imag()

    def _exp_table(self, x):
        """Real exponential lookup leaf: e^x for a 0-d tensor x.
        Out-of-range saturates at the table edge (tensor clamp),
        not a raise. The crosstalk _lerp readout is the only
        non-trivial op; all tensor."""
        xt = self._st(x).clamp(self._EXP_LO, self._EXP_HI)
        return self._lerp(xt, self._EXP_XS, self._EXP_VALUES, self._EXP_DX)

    def _ln_table(self, x):
        """Natural-log lookup leaf: ln(x) for a 0-d tensor x.
        Non-positive / out-of-range saturates at the table edge
        (ln near LN_LO = a large negative - the valid limit)."""
        xt = self._st(x).clamp(self._LN_LO, self._LN_HI)
        return self._lerp(xt, self._LN_XS, self._LN_VALUES, self._LN_DX)

    def _trig_reduce(self, x):
        """Reduce a 0-d angle to (-pi, pi] via x - 2pi*round(x/2pi).
        rotation is periodic so this is the angle it actually turns
        Periodic, so mod 2pi comes for free. Pure tensor."""
        xt = self._st(x)
        return xt - self._TWO_PI * _torch.round(xt / self._TWO_PI)

    def _cos0(self, theta):
        """cos of a 0-d angle via the eigenrotation lookup (the
        x-coordinate of the rotated unit vector)."""
        return self._lerp(self._trig_reduce(theta), self._TRIG_XS, self._COS_VALUES, self._TRIG_DX)

    def _sin0(self, theta):
        """sin of a 0-d angle - same eigenrotation, y-coordinate."""
        return self._lerp(self._trig_reduce(theta), self._TRIG_XS, self._SIN_VALUES, self._TRIG_DX)

    def realExp(self, z):
        """e^(Re z) - the rotational crosstalk lookup leaf, as a
        canonical complex [e^a, 0]. The math.su realExp leaf."""
        return self._mk(self._exp_table(self._re(z)), 0.0)

    def imaginaryExp(self, z):
        """e^(i*Im z) - the eigenrotation: [cos(Im z), sin(Im z)],
        the unit vector at that angle. The math.su imaginaryExp leaf;
        cos/sin are its real/imag projections (cos is its own
        transcendental - the real coordinate of this rotation)."""
        ang = self._im(z)
        return self._mk(self._cos0(ang), self._sin0(ang))

    def cexp(self, z):
        """Complex exponential, the documented keystone:
        exp(a+b*i) = e^a*(cos b + i*sin b) = realExp(z) (x) imaginaryExp(z),
        (x) = complex_mul (the canonical d-dim complex product, verified
        substrate-pure). Returns a canonical complex vector."""
        return self.complex_mul(self.realExp(z), self.imaginaryExp(z))

    def exp(self, x):
        """exp at a scalar-typed boundary = real(cexp(x)). For real x
        (imag 0): realExp=[e^x,0], imaginaryExp=[1,0], product=[e^x,0],
        real part = e^x. This IS the documented real(exp(i*theta))
        projection, not a deviation. 0-d tensor out (back-compat with
        scalar call sites; the full complex op is cexp)."""
        return self._re(self.cexp(self._cnum(x)))

    def ccos(self, z):
        """Complex-argument cosine, the documented reduction
        cos(z) = (e^(i*z) + e^(-i*z)) / 2. Substrate-pure: built
        only from the verified-pure cexp keystone + complex_mul /
        complex_add (no new leaf, no host branch, no scalar
        extraction). i*z and -i*z are complex products with the
        imaginary unit; the /2 is a complex product with [0.5,0]
        so the whole op stays in canonical-complex-vector space.
        For real z (imag 0): i*z = [0, a], cexp = [cos a, sin a],
        -i*z = [0,-a], cexp = [cos a,-sin a], sum/2 = [cos a, 0] -
        identical to the scalar cos() eigenrotation, so the
        paper-cited real cos path is unaffected. For z = a+bi it
        yields cos a*cosh b - i*sin a*sinh b. Canonical complex
        vector out."""
        zc = self._cnum(z)
        iz = self.complex_mul(zc, self._mk(0.0, 1.0))
        miz = self.complex_mul(zc, self._mk(0.0, -1.0))
        half = self._mk(0.5, 0.0)
        return self.complex_mul(self.complex_add(self.cexp(iz), self.cexp(miz)), half)

    def log(self, x):
        """Natural log. Real positive x: ln(x) via the ln leaf. (Full
        complex log - imag part = angle via atan2 - is the documented
        deferred piece, not faked here; real-axis ln matches the
        existing contract and tests.) 0-d tensor out."""
        return self._ln_table(self._re(self._cnum(x)))

    ln = log

    def cos(self, x):
        """cos(theta) = real(exp(i*theta)) - the documented
        definitional reduction. exp(i*theta) = cexp of the PURE-
        IMAGINARY number theta*i (theta on the imag axis), so the
        eigenrotation turns through theta. Real part = cos."""
        itheta = self._mk(0.0, self._st(x))
        return self._re(self.imaginaryExp(itheta))

    def sin(self, x):
        """sin(theta) = imag(exp(i*theta)) - imag part of the same
        pure-imaginary eigenrotation (theta on the imag axis)."""
        itheta = self._mk(0.0, self._st(x))
        return self._im(self.imaginaryExp(itheta))

    def pow(self, x, y):
        """x^y = exp(y*ln x) - change-of-base identity. 0-d tensor."""
        return self.exp(self._st(y) * self.log(x))

    def sqrt(self, x):
        """sqrt(x) = exp(0.5*ln x) - the y=1/2 case of pow."""
        return self.exp(0.5 * self.log(x))

    def tan(self, x):
        """tan = sin/cos. cos->0 gives +/-inf (valid limit; no host if)."""
        return self.sin(x) / self.cos(x)

    def sinh(self, x):
        """(e^x - e^-x)/2."""
        xt = self._st(x)
        return (self.exp(xt) - self.exp(-xt)) * 0.5

    def cosh(self, x):
        """(e^x + e^-x)/2."""
        xt = self._st(x)
        return (self.exp(xt) + self.exp(-xt)) * 0.5

    def tanh(self, x):
        """(e^2x - 1)/(e^2x + 1) [stable]; large |x| => exp saturates
        so tanh -> +/-1, the correct limit, no host range check."""
        e2x = self.exp(2.0 * self._st(x))
        return (e2x - 1.0) / (e2x + 1.0)

    def floor(self, x):
        """Round toward -∞. Substrate: torch.floor (GPU instruction)."""
        return _torch.floor(self._st(x))

    def ceil(self, x):
        """Round toward +∞. Substrate: torch.ceil."""
        return _torch.ceil(self._st(x))

    def round(self, x):
        """Nearest integer, ties-to-even (torch default). JS Math.round
        is half-up — mismatch tracked in the substrate-purity audit."""
        return _torch.round(self._st(x))

    def trunc(self, x):
        """Truncate toward zero. Substrate: torch.trunc."""
        return _torch.trunc(self._st(x))

    def abs(self, x):
        """|x|. Substrate: torch.abs."""
        return _torch.abs(self._st(x))

    def sign(self, x):
        """-1 / 0 / +1. Substrate: torch.sign."""
        return _torch.sign(self._st(x))

    def fmod(self, x, m):
        """Truncation modulus (JS / C / C# / Rust / TS `%`): result
        has the sign of x. x - m·trunc(x/m). Divisor 0 yields a NaN
        tensor — the mathematically-valid degenerate result, not a
        host ZeroDivisionError (no scalar control flow)."""
        xt = self._st(x)
        mt = self._st(m)
        return xt - mt * _torch.trunc(xt / mt)

    def rotation_mod(self, x, m):
        """Floor modulus via the eigenrotation: walk a circle whose
        circumference is m. θ = 2π·x/m, the eigenrotation gives
        (cos θ, sin θ), atan2 reads the phase back, re-wrapped to
        [0, 2π) and scaled by m/2π. Always non-negative for m > 0
        (`rotation_mod(-0.1, 1) == 0.9`); discontinuous at integer
        multiples of m (the atan2 branch cut). Divisor 0 → NaN
        tensor, not a host raise.

        Substrate chain (all tensor ops):
          θ      = 2π · x / m
          (c, s) = cos θ, sin θ            (eigenrotation readout)
          φ      = atan2(s, c)             (tensor; lookup follow-on)
          φ_pos  = φ - 2π·floor(φ / 2π)    (re-wrap to [0, 2π))
          result = m · φ_pos / (2π)
        """
        xt = self._st(x)
        mt = self._st(m)
        theta = self._TWO_PI * xt / mt
        phi = _torch.atan2(self.sin(theta), self.cos(theta))
        phi_pos = phi - self._TWO_PI * _torch.floor(phi / self._TWO_PI)
        return mt * phi_pos / self._TWO_PI

    def sawtooth_mod(self, x, m, n_terms=16):
        """Floor modulus via the Fourier sawtooth — smooth, fully
        differentiable, ~9% Gibbs ring near integer multiples of m.
        mod_floor(x,m) ≈ m/2 - (m/π)·Σ_{k=1..N} sin(2πkx/m)/k.
        The k-sum is a single vectorized tensor reduction (a (K,N)
        crosstalk-weight matmul against the sin table) — NOT a
        Python for-loop over scalars. n_terms is a compile-time
        structural constant, not substrate data."""
        xt = self._st(x)
        mt = self._st(m)
        k = _torch.arange(1, int(n_terms) + 1, dtype=self.dtype, device=self.device)
        ang = self._TWO_PI * k * xt / mt
        ar = ang - self._TWO_PI * _torch.round(ang / self._TWO_PI)
        d = (self._TRIG_XS.unsqueeze(0) - ar.unsqueeze(1)).abs() / self._TRIG_DX
        w = (1.0 - d).clamp(min=0.0)
        sines = _torch.matmul(w, self._SIN_VALUES)
        total = (sines / k).sum()
        return 0.5 * mt - (mt / 3.141592653589793) * total

    # `mod` is the canonical floor-mod alias — today the
    # eigenrotation form (Emma-preferred default).
    mod = rotation_mod

    def transpose(self, m):
        """Transpose (last two dims for 2-D+; identity for 1-D)."""
        if m.ndim < 2:
            return m
        return _torch.transpose(m, -2, -1)

    def norm(self, v):
        """L2 norm. Scalar result."""
        return float(_torch.linalg.norm(v))

    def normalize(self, v):
        """L2-normalize with an eps-guard so zero-norm input returns zero."""
        n = _torch.linalg.norm(v)
        return v / (n + _torch.finfo(self.dtype).tiny)

    def rotation_for(self, role):
        """Cached Haar-random orthogonal rotation matrix for the role vector."""
        return self._rotation_for(role)

    MatrixMul = matmul
    TensorProduct = tensor_product
    Outer = outer
    Dot = dot
    Transpose = transpose
    Norm = norm
    Normalize = normalize
    RotationFor = rotation_for

    # ---- Vector component accessors (debugging / teaching) ----

    def component(self, v, i):
        """Return element i of v over the full extended state vector."""
        return float(v[int(i)].item())

    def semantic(self, v, i):
        """Return element i within the semantic block."""
        idx = int(i)
        if idx < 0 or idx >= self.semantic_dim:
            raise IndexError(
                f"semantic index {idx} out of range [0, {self.semantic_dim})")
        return float(v[idx].item())

    def synthetic(self, v, i):
        """Return element i within the synthetic block."""
        idx = int(i)
        if idx < 0 or idx >= self.synthetic_dim:
            raise IndexError(
                f"synthetic index {idx} out of range [0, {self.synthetic_dim})")
        return float(v[self.semantic_dim + idx].item())

    # ---- Canonical-axis accessors (real/imag/truth) ----

    def real(self, v):
        return float(v[self.semantic_dim + self.AXIS_REAL].item())

    def imag(self, v):
        return float(v[self.semantic_dim + self.AXIS_IMAG].item())

    def truth(self, v):
        return float(v[self.semantic_dim + self.AXIS_TRUTH].item())

    def make_real(self, x):
        v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
        v[self.semantic_dim + self.AXIS_REAL] = float(x)
        return v

    def make_complex(self, re, im):
        v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
        v[self.semantic_dim + self.AXIS_REAL] = float(re)
        v[self.semantic_dim + self.AXIS_IMAG] = float(im)
        return v

    def _swap_ri_matrix(self):
        if not hasattr(self, '_swap_ri_cache') or self._swap_ri_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            r = self.semantic_dim + self.AXIS_REAL
            i = self.semantic_dim + self.AXIS_IMAG
            M[r, i] = 1.0; M[i, r] = 1.0
            self._swap_ri_cache = M
        return self._swap_ri_cache

    def _cm_real_matrix(self):
        if not hasattr(self, '_cm_real_cache') or self._cm_real_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            r = self.semantic_dim + self.AXIS_REAL
            i = self.semantic_dim + self.AXIS_IMAG
            M[r, r] = 1.0; M[r, i] = -1.0
            self._cm_real_cache = M
        return self._cm_real_cache

    def _cm_imag_matrix(self):
        if not hasattr(self, '_cm_imag_cache') or self._cm_imag_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            r = self.semantic_dim + self.AXIS_REAL
            i = self.semantic_dim + self.AXIS_IMAG
            M[i, r] = 1.0; M[i, i] = 1.0
            self._cm_imag_cache = M
        return self._cm_imag_cache

    def complex_mul(self, a, b):
        """Complex product: matrix form, no scalar extraction.

        c = _cm_real @ (a * b) + _cm_imag @ ((_swap_ri @ a) * b)
        """
        av = self._as_complex_vector(a)
        bv = self._as_complex_vector(b)
        ab = av * bv
        swapped_ab = (self._swap_ri_matrix() @ av) * bv
        return self._cm_real_matrix() @ ab + self._cm_imag_matrix() @ swapped_ab

    def complex_add(self, a, b):
        """Complex addition. Coerces both operands to complex vectors
        first so `complex + scalar` adds to the real axis only
        rather than broadcasting across imag too."""
        return self._as_complex_vector(a) + self._as_complex_vector(b)

    def complex_sub(self, a, b):
        """Complex subtraction. Same coercion pattern as complex_add."""
        return self._as_complex_vector(a) - self._as_complex_vector(b)

    def _conj_matrix(self):
        """Cached d×d matrix that conjugates a complex vector: identity
        on every axis except imag, where it negates. Built lazily on
        first call, then reused; same pattern as _cm_real_matrix."""
        if not hasattr(self, '_conj_cache') or self._conj_cache is None:
            M = _torch.eye(self.dim, dtype=self.dtype, device=self.device)
            i = self.semantic_dim + self.AXIS_IMAG
            M[i, i] = -1.0
            self._conj_cache = M
        return self._conj_cache

    def _broadcast_real_matrix(self):
        """Cached d×d matrix that broadcasts the real-axis value of a
        vector to every axis: column real_axis is all-ones, everything
        else is zero. `M @ v` returns a vector whose every element is
        v[real_axis]. Used by complex_div to turn the scalar |b|² on
        the real axis into a vector-wide divisor without scalar
        extraction."""
        if not hasattr(self, '_br_real_cache') or self._br_real_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            r = self.semantic_dim + self.AXIS_REAL
            M[:, r] = 1.0
            self._br_real_cache = M
        return self._br_real_cache

    def complex_div(self, a, b):
        """Complex division: (a+bi)/(c+di) = ((ac+bd) + (bc-ad)i)/(c²+d²).
        Substrate-pure throughout — no scalar extraction from the
        vector. Three substrate steps:
          1. conj_b = _conj_matrix @ bv          (negate imag axis)
          2. num    = complex_mul(av, conj_b)    (numerator complex)
          3. denom_v = _broadcast_real @ complex_mul(bv, conj_b)
                       (broadcast c²+d² to every axis)
          return num / denom_v                   (element-wise div)
        Division by a zero divisor produces inf/NaN on the real and
        imag axes, matching Python complex division semantics."""
        av = self._as_complex_vector(a)
        bv = self._as_complex_vector(b)
        conj_b = self._conj_matrix() @ bv
        num = self.complex_mul(av, conj_b)
        denom_complex = self.complex_mul(bv, conj_b)
        denom_vec = self._broadcast_real_matrix() @ denom_complex
        return num / denom_vec

    def _as_complex_vector(self, x):
        """Coerce Python scalar / tensor to complex-plane form."""
        if isinstance(x, _torch.Tensor):
            if x.dim() == 0:
                # 0-d scalar tensor (e.g. a slot-loaded int or a loop
                # state var): lift its value onto the real axis of a
                # number-vector, on-device, so number ops (gt / lt /
                # add / ...) receive a proper complex-plane vector
                # rather than a bare scalar (which breaks the matmul).
                v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
                v[self.semantic_dim + self.AXIS_REAL] = x
                return v
            return x
        if isinstance(x, bool):
            return self.make_real(1.0 if x else 0.0)
        return self.make_real(float(x))

    def make_truth(self, t):
        v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
        v[self.semantic_dim + self.AXIS_TRUTH] = float(t)
        return v

    def make_char(self, codepoint):
        """Character literal: a 1-character String. Equivalent to
        make_string(chr(codepoint)). The `char` type is now a
        1-character String; AXIS_CHAR_FLAG is an alias for
        AXIS_STRING_FLAG."""
        return self.make_string(chr(int(codepoint)))

    def is_char(self, v):
        """True iff v is a String value (kept as `is_char` for
        backward-compat with code that pre-dated the rename to
        AXIS_STRING_FLAG; new code should use is_string)."""
        return bool(v[self.semantic_dim + self.AXIS_STRING_FLAG].item() >= 0.5)

    # ---- String runtime methods ----
    # Encoding: AXIS_STRING_FLAG marks the vector as a String.
    # Characters pack into the synthetic axes — char[0] at
    # AXIS_REAL (=synthetic[0]), char[1] at AXIS_IMAG
    # (=synthetic[1]), char[k] for k>=2 at synthetic[k+3]
    # (skipping AXIS_TRUTH/STRING_FLAG/LOOP_DONE at synthetic
    # [2..4]). Length is recovered by walking from the highest
    # possible char position down to the first non-zero. See
    # planning/sutra-spec/strings.md.
    def _string_axis(self, char_index):
        """Map a character index k into the absolute axis offset
        inside the synthetic block (relative to semantic_dim)."""
        return char_index if char_index < 2 else char_index + 3

    def string_max_length(self):
        """Maximum string length that fits in the current
        synthetic_dim. char positions occupy synthetic[0,1] plus
        synthetic[5..synthetic_dim-1]."""
        if self.synthetic_dim < 5:
            return min(self.synthetic_dim, 2)
        return 2 + (self.synthetic_dim - 5)

    def _str_axes(self):
        """Cached constant LongTensor of the absolute vector offsets
        that hold the String codepoints, in char order: offset k =
        semantic_dim + (k if k<2 else k+3), for k in 0..max_len-1.
        Built once at first use (a compile-time-shaped constant, the
        same class as the exp/trig lookup tables) so string_length /
        char_at / concat are pure tensor gather/scatter over the
        codepoint block instead of host codepoint loops."""
        if not hasattr(self, '_str_axes_cache') or self._str_axes_cache is None:
            ml = self.string_max_length()
            offs = [self.semantic_dim + (k if k < 2 else k + 3) for k in range(ml)]
            self._str_axes_cache = _torch.tensor(offs, dtype=_torch.long, device=self.device)
        return self._str_axes_cache

    def make_string(self, s):
        """Construct a String value from a Python str."""
        if not isinstance(s, str):
            s = str(s)
        max_len = self.string_max_length()
        # Saturate, do not raise (no-runtime-errors-by-mechanism):
        # a literal longer than the synthetic budget truncates at
        # the cap rather than throwing. This enumerate is the
        # host-literal -> substrate ENTRY boundary (the make_real /
        # _st analogue), not an op-internal substrate read.
        s = s[:max_len]
        v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
        v[self.semantic_dim + self.AXIS_STRING_FLAG] = 1.0
        for k, ch in enumerate(s):
            axis = self._string_axis(k)
            v[self.semantic_dim + axis] = float(ord(ch))
        return v

    def is_string(self, v):
        """True iff v has the AXIS_STRING_FLAG set."""
        return bool(v[self.semantic_dim + self.AXIS_STRING_FLAG].item() >= 0.5)

    def string_length(self, v):
        """Length of String v, substrate-pure (Audit REAL LEAK #5;
        was a host `for k in range`, `.item()`, host `if`, host
        `return k+1`). Gather the codepoint block, mark non-zero
        positions, take the highest 1-based position that is
        non-zero: length = max((k+1) where cps[k] != 0). All tensor
        ops; 0-d tensor out. Trailing-zero-as-sentinel preserved
        (a 0 codepoint in the tail reads shorter, same as before)."""
        ax = self._str_axes()
        cps = v.index_select(0, ax)
        nz = (cps != 0).to(self.dtype)
        pos = _torch.arange(1, ax.shape[0] + 1, dtype=self.dtype, device=self.device)
        return (pos * nz).max()

    def string_char_at(self, v, i):
        """Codepoint at position i, substrate-pure (Audit REAL LEAK
        #5; was `int(i)`, host `if i<0 or i>=...`, `int(.item())`).
        Gather the codepoint block, mask out-of-range to 0 (saturate,
        no host branch/raise). 0-d tensor out."""
        ax = self._str_axes()
        n = ax.shape[0]
        it = self._st(i)
        valid = ((it >= 0) & (it < n)).to(self.dtype)
        ci = it.clamp(0, n - 1).long()
        cps = v.index_select(0, ax)
        return cps[ci] * valid

    def wrap(self, value):
        """JavaScriptObject.wrap(x) — lift a primitive (int /
        float / string / bool) into a JavaScriptObject. Just
        routes through `_as_any_vector` which already handles
        the primitive-to-vector coercion."""
        return self._as_any_vector(value)

    def js_add(self, a, b):
        """JavaScriptObject.js_add(a, b) — JavaScript-coercive `+`.
        If either operand has AXIS_STRING_FLAG set, dispatches to
        string_concat. Otherwise element-wise vector add (numeric
        path). Per Emma 2026-05-10: this is how the JSO override
        absorbs JS\'s coercive + semantics.
        """
        av = self._as_any_vector(a)
        bv = self._as_any_vector(b)
        # String coercion: if either side carries the string flag,
        # concatenate them as strings. Promote a numeric operand to
        # a string by reading its real-axis value and calling str().
        if self.is_string(av) or self.is_string(bv):
            a_str = av if self.is_string(av) else self.make_string(str(int(self.real(av))) if float(self.real(av)).is_integer() else str(self.real(av)))
            b_str = bv if self.is_string(bv) else self.make_string(str(int(self.real(bv))) if float(self.real(bv)).is_integer() else str(self.real(bv)))
            return self.string_concat(a_str, b_str)
        return av + bv

    def js_strict_eq(self, a, b):
        """JavaScriptObject.js_strict_eq(a, b) — Sutra interpretation
        of `===` per Emma 2026-05-10:
            bool operator ===(var a, var b) {
                return defuzzify(a == b);
            }
        More strictness than the substrate `==` (which is cosine-
        fuzzy similarity) — the defuzzify polarizes the fuzzy
        result along the truth axis. NOT JavaScript reference-
        equality; explicitly redefined for the Sutra surface.
        """
        av = self._as_any_vector(a)
        bv = self._as_any_vector(b)
        # Strict equality via element-wise difference norm.
        # Cosine + defuzzify_trit polarizes 'similar but not
        # identical' to the neutral 0, which is wrong for JS
        # `===` (wants binary true/false). Using the diff norm
        # instead: ||a - b|| ≈ 0 iff a and b are component-wise
        # equal. tanh(c - k*||a-b||) maps to +1 at zero diff and
        # saturates to -1 quickly for any non-zero diff.
        import math as _math
        diff_norm = float(_torch.linalg.norm(av - bv))
        truth = _math.tanh(5.0 - 100.0 * diff_norm)
        return self.make_truth(truth)

    def js_strict_neq(self, a, b):
        """JavaScriptObject.js_strict_neq(a, b) — `!==` (negation
        of `===`). Computes js_strict_eq, then flips the truth
        axis: a +1 result becomes -1 and vice versa."""
        eq = self.js_strict_eq(a, b)
        # Flip the truth-axis component. Vector clone so we don't
        # mutate the input.
        out = eq.clone()
        out[self.semantic_dim + self.AXIS_TRUTH] = -float(eq[self.semantic_dim + self.AXIS_TRUTH].item())
        return out

    def js_loose_eq(self, a, b):
        """JavaScriptObject.js_loose_eq(a, b) — JavaScript `==`
        with type coercion. If one side is a string and the
        other is a number, coerce the number to a string and
        compare. If one side is a bool, coerce the bool to a
        number (true=1, false=0) and compare. Otherwise falls
        through to strict equality.
        """
        av = self._as_any_vector(a)
        bv = self._as_any_vector(b)
        a_is_str = self.is_string(av)
        b_is_str = self.is_string(bv)
        # String-vs-number coercion: promote the non-string to a
        # string and compare codepoints.
        if a_is_str and not b_is_str:
            r = self.real(bv)
            b_promoted = self.make_string(str(int(r)) if float(r).is_integer() else str(r))
            return self.js_strict_eq(av, b_promoted)
        if b_is_str and not a_is_str:
            r = self.real(av)
            a_promoted = self.make_string(str(int(r)) if float(r).is_integer() else str(r))
            return self.js_strict_eq(a_promoted, bv)
        # Same kind (both strings or both numbers): defer to strict.
        return self.js_strict_eq(av, bv)

    def js_loose_neq(self, a, b):
        """JavaScriptObject.js_loose_neq(a, b) — `!=` (negation
        of loose `==`)."""
        eq = self.js_loose_eq(a, b)
        out = eq.clone()
        out[self.semantic_dim + self.AXIS_TRUTH] = -float(eq[self.semantic_dim + self.AXIS_TRUTH].item())
        return out

    def _js_str_cmp(self, av, bv):
        """Lexicographic compare of two String values. Returns
        -1, 0, +1 (memcmp-style). First differing codepoint
        decides; shorter-with-matching-prefix is less. Host
        int arithmetic over codepoint axes (JS-interop
        compat boundary)."""
        ax = self._str_axes()
        a_cps = av.index_select(0, ax)
        b_cps = bv.index_select(0, ax)
        la = int(self.string_length(av).item())
        lb = int(self.string_length(bv).item())
        n = min(la, lb)
        for i in range(n):
            ai = int(a_cps[i].item())
            bi = int(b_cps[i].item())
            if ai != bi:
                return -1 if ai < bi else 1
        if la == lb:
            return 0
        return -1 if la < lb else 1

    def _js_relational(self, a, b, op):
        """ECMAScript Abstract Relational Comparison core. `op`
        is one of "<", ">", "<=", ">=". Both-string → lex compare;
        otherwise numeric on AXIS_REAL. NaN on either side → false
        (returns make_truth(-1.0))."""
        av = self._as_any_vector(a)
        bv = self._as_any_vector(b)
        if self.is_string(av) and self.is_string(bv):
            c = self._js_str_cmp(av, bv)
            if op == "<":
                return self.make_truth(1.0 if c < 0 else -1.0)
            if op == ">":
                return self.make_truth(1.0 if c > 0 else -1.0)
            if op == "<=":
                return self.make_truth(1.0 if c <= 0 else -1.0)
            return self.make_truth(1.0 if c >= 0 else -1.0)
        # Numeric path: coerce to real-axis scalars and compare.
        # NaN on either side → false for all four operators
        # (ECMAScript IsLessThan returns undefined → false).
        ra = self.real(av)
        rb = self.real(bv)
        if ra != ra or rb != rb:
            return self.make_truth(-1.0)
        if op == "<":
            return self.make_truth(1.0 if ra < rb else -1.0)
        if op == ">":
            return self.make_truth(1.0 if ra > rb else -1.0)
        if op == "<=":
            return self.make_truth(1.0 if ra <= rb else -1.0)
        return self.make_truth(1.0 if ra >= rb else -1.0)

    def js_lt(self, a, b):
        """JavaScriptObject.js_lt(a, b) — JS `<` with type
        coercion. Both-string → lex compare; otherwise numeric
        compare on AXIS_REAL. NaN on either side → false."""
        return self._js_relational(a, b, "<")

    def js_gt(self, a, b):
        """JavaScriptObject.js_gt(a, b) — JS `>` with type
        coercion (symmetric to js_lt with operands swapped)."""
        return self._js_relational(a, b, ">")

    def js_le(self, a, b):
        """JavaScriptObject.js_le(a, b) — JS `<=`. NOT defined as
        !(a > b) because of NaN: under JS semantics both `a > b`
        and `a <= b` are false when either side is NaN, so the
        negation identity fails. Explicit comparison instead."""
        return self._js_relational(a, b, "<=")

    def js_ge(self, a, b):
        """JavaScriptObject.js_ge(a, b) — JS `>=`. Same NaN-safety
        reasoning as js_le."""
        return self._js_relational(a, b, ">=")

    def js_truthy(self, a):
        """JavaScriptObject.js_truthy(a) — JS truthy/falsy table.
        Falsy: 0, "", null, undefined, NaN, false. Everything else
        truthy. Returns a polarized fuzzy on the truth axis (+1
        truthy, -1 falsy).
        """
        av = self._as_any_vector(a)
        # Strings: falsy iff length zero.
        if self.is_string(av):
            truthy = 1.0 if self.string_length(av) > 0 else -1.0
            return self.make_truth(truthy)
        # Numbers (real-axis scalars): falsy iff exactly zero. NaN
        # is also falsy in JS — torch.isnan handles it.
        r = self.real(av)
        import math as _math
        if r != r or r == 0.0:
            return self.make_truth(-1.0)
        return self.make_truth(1.0)

    def js_typeof(self, a):
        """JavaScriptObject.js_typeof(a) — returns a substrate
        String carrying one of: "number", "string", "boolean",
        "object", "undefined". Detected by reading the value\'s
        flag axes; defaults to "number" when no specific flag is
        set (the most common case for transpiled TS values).
        """
        av = self._as_any_vector(a)
        if self.is_string(av):
            return self.make_string("string")
        # All other detection paths fall back to number — Sutra
        # doesn't have a runtime distinction between numbers and
        # bare vectors today. Object / boolean / undefined
        # discrimination needs prototype-chain support and the
        # AXIS_AXON_POPULATED sentinel, both partial today.
        return self.make_string("number")

    def string_concat(self, a, b):
        """Concatenate two String values. Reads codepoints from a
        then b into a fresh String vector. Overflow (a-len + b-len
        exceeds string_max_length) raises — the synthetic budget is
        a hard cap. 2026-05-08 addition for TS string + string."""
        # Substrate-pure (Audit REAL LEAK #5; was string_length host
        # ints + `if la+lb>max: raise` + two host `for` copy loops).
        # Concat = shift b right by len(a) and add: a permutation
        # (gather by a shifted index) of the codepoint block, the
        # VSA-native operation Emma specified. Overflow positions
        # fall off the gather mask = saturate, no raise (no-runtime-
        # errors-by-mechanism). All tensor ops.
        ax = self._str_axes()
        n = ax.shape[0]
        la = self.string_length(a)
        a_cps = a.index_select(0, ax)
        b_cps = b.index_select(0, ax)
        src = _torch.arange(n, dtype=self.dtype, device=self.device) - la
        sv = ((src >= 0) & (src < n)).to(self.dtype)
        b_shift = b_cps[src.clamp(0, n - 1).long()] * sv
        out_cps = a_cps + b_shift
        v = _torch.zeros(self.dim, dtype=self.dtype, device=self.device)
        v[self.semantic_dim + self.AXIS_STRING_FLAG] = 1.0
        v = v.index_copy(0, ax, out_cps)
        return v

    def string_to_python(self, v):
        """Decode a String value back to a Python str. This is the
        substrate -> host MONITORING / decode boundary (CLAUDE.md
        explicitly allows decoding substrate output for reporting),
        the analogue of argmax_cosine returning a host index at the
        terminal commit. The int()/.item() here are AT that boundary,
        not inside a substrate op definition. string_length is now a
        0-d tensor, so coerce once here for the host range."""
        n = int(self.string_length(v).item())
        chars = []
        for i in range(n):
            axis = self._string_axis(i)
            chars.append(chr(int(v[self.semantic_dim + axis].item())))
        return "".join(chars)

    def make_trit(self, t):
        """Three-valued primitive class — aliases make_truth."""
        return self.make_truth(t)

    def defuzzify_trit(self, v, iters=10, beta=2.0):
        """Three-way polarizer toward {-1, 0, +1}. Substrate-pure
        (Audit REAL LEAK #2; was float(v[..].item()) + host for-range
        + _math.exp + float(x) writeback). Reads the truth axis as a
        0-d tensor view (no .item()/float()), runs the spec-fixed
        10-step beta-sharpening as a straight-line tensor-op chain
        unrolled at codegen time (like the defuzzy loop(10): the
        unrolled form is what the fusion pass targets), each step
        three substrate-pure self.exp readouts, then a 0-d-tensor
        scatter back onto the truth axis. The iters arg is kept for
        signature compat; the spec definition is 10, like defuzzy."""
        idx = self.semantic_dim + self.AXIS_TRUTH
        x = v[idx]
        b = self._st(beta)
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        w_neg = self.exp(-b * (x + 1.0) ** 2)
        w_zero = self.exp(-b * x ** 2)
        w_pos = self.exp(-b * (x - 1.0) ** 2)
        s = w_neg + w_zero + w_pos
        x = (-w_neg + w_pos) / s
        b = b * 2.0
        out = v.clone()
        out[idx] = x
        return out

    # ---- Logical operators — smooth polynomial form ----
    #
    # Same Lagrange-derived polynomials as the numpy backend:
    #   min(a, b) = (a + b + ab - a² - b² + a²b²) / 2
    #   max(a, b) = (a + b - ab + a² + b² - a²b²) / 2
    # Exact on {-1, 0, +1}², C^∞ everywhere, CUDA via torch ops.

    def _as_truth_vector(self, x):
        """Return x as a tensor. Scalar / bool → make_truth."""
        if isinstance(x, _torch.Tensor):
            return x
        if isinstance(x, bool):
            return self.make_truth(1.0 if x else -1.0)
        return self.make_truth(float(x))

    # ---- Ordered comparison — pure tensor ops, no branches ----

    def _real_projector(self):
        """Diagonal real-axis projector. Cached tensor on device."""
        if not hasattr(self, '_real_proj_cache') or self._real_proj_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            idx = self.semantic_dim + self.AXIS_REAL
            M[idx, idx] = 1.0
            self._real_proj_cache = M
        return self._real_proj_cache

    def _truth_from_real(self):
        """Matrix moving the real-axis entry to the truth axis."""
        if not hasattr(self, '_t_from_r_cache') or self._t_from_r_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            M[self.semantic_dim + self.AXIS_TRUTH,
                self.semantic_dim + self.AXIS_REAL] = 1.0
            self._t_from_r_cache = M
        return self._t_from_r_cache

    CMP_SLOPE = 100.0

    def gt(self, a, b):
        """a > b — differentiable tanh on real-axis difference."""
        av = self._as_complex_vector(a)
        bv = self._as_complex_vector(b)
        diff_r = self._real_projector() @ (av - bv)
        signed = _torch.tanh(self.CMP_SLOPE * diff_r)
        return self._truth_from_real() @ signed

    # ---- Equality — cosine similarity on tensors ----

    def eq(self, a, b):
        """a == b — cosine similarity, eps-guarded divide, no branch."""
        av = self._as_any_vector(a)
        bv = self._as_any_vector(b)
        na = _torch.sqrt((av * av).sum())
        nb = _torch.sqrt((bv * bv).sum())
        cos = (av * bv).sum() / (na * nb + _torch.finfo(self.dtype).tiny)
        return self.make_truth(float(cos.item()))

    def eq_synthetic(self, a, b):
        """Synthetic-axis equality — 1 - 2*tanh(||a - b||)."""
        av = self._as_any_vector(a)
        bv = self._as_any_vector(b)
        diff = av - bv
        dist = _torch.sqrt((diff * diff).sum())
        truth = 1.0 - 2.0 * _torch.tanh(dist)
        return self.make_truth(float(truth.item()))

    def neq_synthetic(self, a, b):
        """!= for synthetic-axis values — negation of eq_synthetic."""
        return -self.eq_synthetic(a, b)

    def _as_any_vector(self, x):
        """Coerce any runtime value to a d-dim tensor for comparison.

        Python str → make_string (NOT embed): all callers
        (js_add, js_strict_eq, js_loose_eq, js_typeof, js_truthy,
        js_lt/gt/le/ge, eq_synthetic, neq_synthetic) inspect the
        AXIS_STRING_FLAG via is_string() to dispatch — embedding
        the string would clear the flag and break all of them.
        Fixed 2026-05-20 when the JSO ordered-comparison work
        exposed the pre-existing js_add/loose_eq/typeof/truthy
        latent bug. JS-interop carve-out (CLAUDE.md "Vibe-coded
        projects" §"intentional compatibility code")."""
        if isinstance(x, _torch.Tensor):
            return x
        if isinstance(x, bool):
            return self.make_truth(1.0 if x else -1.0)
        if isinstance(x, (int, float)):
            return self.make_real(float(x))
        if isinstance(x, str):
            return self.make_string(x)
        raise TypeError(f'cannot coerce {type(x).__name__} to a tensor for comparison')

    # ---- Defuzzification — torch version ----

    def _truth_projector(self):
        """Diagonal dim×dim projector onto truth axis. Cached tensor."""
        if not hasattr(self, '_truth_proj_cache') or self._truth_proj_cache is None:
            M = _torch.zeros((self.dim, self.dim), dtype=self.dtype, device=self.device)
            idx = self.semantic_dim + self.AXIS_TRUTH
            M[idx, idx] = 1.0
            self._truth_proj_cache = M
        return self._truth_proj_cache


    def make_random_rotation(self, angle, n_planes=1, seed=None):
        """Block-diagonal Haar rotation, scaled by fractional power.

        Seeded by numpy's RandomState for deterministic Haar-uniformity;
        the result is converted to a torch tensor on self.device. Used
        by eigenrotation loops.
        """
        import numpy as _np_bridge
        rng = _np_bridge.random.RandomState(seed if seed is not None else self.seed)
        A = rng.randn(self.semantic_dim, self.semantic_dim)
        Q_sem_np, _ = _np_bridge.linalg.qr(A)
        w, V = _np_bridge.linalg.eig(Q_sem_np)
        phases = _np_bridge.angle(w) * (angle / _np_bridge.pi)
        R_sem_np = _np_bridge.real((V * _np_bridge.exp(1j * phases)) @ _np_bridge.linalg.inv(V))
        R_sem = _torch.as_tensor(R_sem_np, dtype=self.dtype, device=self.device)
        R = _torch.eye(self.dim, dtype=self.dtype, device=self.device)
        R[:self.semantic_dim, :self.semantic_dim] = R_sem
        return R

    def compile_prototypes(self, prototype_vectors, frame_seed=None):
        return dict(prototype_vectors)

    def _step(self, state, R, target, halted, k, threshold, eps=1e-12):
        """RNN cell: one branchless tail-recursive loop step (torch tensor ops)."""
        cand = R @ state
        cand = cand / (_torch.linalg.norm(cand) + eps)
        sim = _torch.dot(cand, target) / (_torch.linalg.norm(target) + eps)
        halt = 1.0 / (1.0 + _torch.exp(-k * (sim - threshold)))
        one = _torch.tensor(1.0, dtype=self.dtype, device=self.device)
        halted = _torch.minimum(halted + halt, one)
        state = (1.0 - halted) * cand + halted * state
        return state, halted

    def loop(self, initial_state, rotation, compiled_prototypes,
        target_name=None, threshold=0.5, max_iters=50, k=20.0, frame_seed=None):
        """Branchless RNN-style tail-recursive loop cell (torch backend).

        Same semantics as the numpy backend. T-step unroll, soft halt via
        sigmoid, output gating via AXIS_LOOP_DONE. Autograd-friendly:
        every op is differentiable with respect to state, target, threshold.
        """
        state = initial_state.clone()
        halted = _torch.tensor(0.0, dtype=self.dtype, device=self.device)
        iters_active = _torch.tensor(0.0, dtype=self.dtype, device=self.device)
        if target_name is not None:
            target = compiled_prototypes[target_name]
        else:
            target = next(iter(compiled_prototypes.values()))
        for _t in range(max_iters):
            iters_active = iters_active + (1.0 - halted)
            state, halted = self._step(state, rotation, target, halted, k, threshold)
        # Output gating: scale value axes by halted; mark AXIS_LOOP_DONE.
        gated = state * halted
        gated[self.semantic_dim + self.AXIS_LOOP_DONE] = halted
        return target_name, gated, iters_active


_VSA = _TorchVSA(semantic_dim=8, synthetic_dim=100, seed=42, llm_model='unused-no-basis-vectors')
AXON_KEYS_BOUND = frozenset([])
AXON_KEYS_READ = frozenset([])


def _argmax_cosine(query, candidates):
    """Vectorized cosine argmax on torch tensors.

    Stacks candidates into (N, d), computes all N cosines as one
    matmul against the query, returns the candidate at the argmax.
    This is the GPU-shaped form: O(1) big kernel, not O(N) small ones.

    Note: SutraDB integration (queue item 2) does NOT route through
    here — see _VSA.nearest_string for the embedded-DB decode path.
    argmax_cosine takes a runtime candidate-vector list; SutraDB is
    the compile-time-populated string-to-embedding store.
    """
    if not candidates:
        return None
    M = _torch.stack([
        _torch.as_tensor(c, dtype=_DTYPE, device=_DEVICE)
        for c in candidates
    ])
    q = _torch.as_tensor(query, dtype=_DTYPE, device=_DEVICE)
    row_norms = _torch.linalg.norm(M, dim=1)
    q_norm = _torch.linalg.norm(q)
    # eps-guard q_norm the same way row_norms is guarded below
    # (Audit REAL LEAK #7 — was `if float(q_norm) == 0: return
    # candidates[0]`, a data-dependent host branch). Zero query
    # norm → M@q is the zero vector → all scores equal → argmax
    # picks index 0, exactly the old behaviour, no host branch.
    safe_qn = _torch.where(q_norm > 0, q_norm, _torch.ones_like(q_norm))
    safe_rn = _torch.where(row_norms > 0, row_norms, _torch.ones_like(row_norms))
    scores = (M @ q) / (safe_rn * safe_qn)
    neg_inf = _torch.full_like(scores, float('-inf'))
    scores = _torch.where(row_norms > 0, scores, neg_inf)
    return candidates[int(_torch.argmax(scores).item())]


def _select_softmax(scores, options):
    """Softmax-weighted superposition of option vectors (torch)."""
    s = _torch.as_tensor(scores, dtype=_DTYPE, device=_DEVICE)
    s = s - _torch.amax(s)
    w = _torch.exp(s)
    w = w / _torch.sum(w)
    opts = _torch.stack([
        _torch.as_tensor(o, dtype=_DTYPE, device=_DEVICE)
        for o in options
    ])
    return (w[:, None] * opts).sum(dim=0)

def _vector_map_lookup(pairs, key):
    """Cosine-argmax lookup for vector-keyed maps.

    Stacks the codebook keys into a single substrate matrix at
    call time, runs one matmul + argmax against the query, and
    returns the value at the matching index. No host control
    flow on the runtime path.
    """
    if not pairs:
        return None
    keys = _torch.stack([
        _torch.as_tensor(k, dtype=_DTYPE, device=_DEVICE)
        for k, _ in pairs
    ])
    q = _torch.as_tensor(key, dtype=_DTYPE, device=_DEVICE)
    row_norms = _torch.linalg.norm(keys, dim=1)
    q_norm = _torch.linalg.norm(q)
    safe_rn = _torch.where(row_norms > 0, row_norms, _torch.ones_like(row_norms))
    safe_qn = _torch.where(q_norm > 0, q_norm, _torch.ones_like(q_norm))
    scores = (keys @ q) / (safe_rn * safe_qn)
    neg_inf = _torch.full_like(scores, float('-inf'))
    scores = _torch.where(row_norms > 0, scores, neg_inf)
    return pairs[int(_torch.argmax(scores).item())][1]

def String_operator_plus(a, b):
    _program_halt = 1.0
    return (_VSA.string_concat(a, b)) * _program_halt

def step(n):
    _program_halt = 1.0
    return (_VSA.make_real((n + 1.0))) * _program_halt

def pixel(x, y, n):
    _program_halt = 1.0
    cx = ((((2.0 * n) / 9.0)) - 1.0)
    dx = (x - cx)
    return (_VSA.make_real(((1.0 - (dx * dx)) - (y * y)))) * _program_halt

def main():
    _program_halt = 1.0
    return (step(0.0)) * _program_halt

