"""Generate apps/font/font.su from tools/font_data.py (Emma 2026-05-26).

The .su file is long but mechanical — 36 letter functions, each a 25-way
position select; plus an outer 36-way letter select. Hand-writing this is
both error-prone and obscures intent. Generate it from font_data.py instead,
so the font shape lives in one place (the data) and the substrate dispatch
shape lives in one place (this generator).

Re-run after editing tools/font_data.py:

    python tools/generate_font_su.py

The generator does not run on the substrate; it is build-time tooling that
emits .su source. The .su that gets shipped IS what the substrate executes.
"""
from __future__ import annotations

import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from font_data import CHARS_ORDER, FONT_5x5, bits_for


_HEADER = """\
// font.su -- GENERATED by tools/generate_font_su.py from tools/font_data.py.
// DO NOT EDIT BY HAND -- regenerate via `python tools/generate_font_su.py`.
//
// Emma's text-input demo (2026-05-26): each keypress shows the typed character
// as a 5x5 pixel glyph on the substrate. Two substrate computations:
//
//   step(prev_state, x, y, char_code)
//       Emma's recurrent step. The current pixel value at (x, y) is the
//       state; on a new keypress, `state = prev*0 + glyph_pixel(...)` --
//       explicit substrate "forget then add", same shape as toggle.su's flip
//       and count.su's +1. The * 0 is the substrate's way of saying "discard
//       previous state"; the +/glyph is the substrate's way of saying "the
//       new input is now what's on screen."
//
//   glyph_pixel(x, y, char_code)
//       Returns 1.0 if pixel (x, y) is lit for the letter with this codepoint,
//       else 0.0. Decided ON THE SUBSTRATE: 36-way defuzzified `select` over
//       A-Z + 0-9, made one-hot by softmax saturation (scores
//       -1000*(char_code - target_code)^2 -> exp underflows to exact 0 in
//       float32 AND float64, so the selected branch passes through and the
//       others are zeroed by exact-zero weights -- the same one-hot trick
//       apps/calc/switch.su uses for operator dispatch).
//
//   bit_<C>(pos) (helpers, one per of the 36 chars)
//       The lit/unlit bit for character <C> at flat position pos = y*5 + x
//       (pos in 0..24). Same defuzzified-select pattern, 25-way over pos.
//
// Together: keypress -> char_code -> outer select over 36 letters
//                 -> inner select over 25 positions -> 1.0 or 0.0.
// No host font table on the runtime path; the lit/unlit decision is the
// substrate's. Host stays I/O: parse the keypress, paint the result.
"""


def gen_bit_function(char: str) -> str:
    """One ``bit_<C>(scalar pos)`` returning the lit/unlit bit for char at pos."""
    bits = bits_for(char)
    lines: list[str] = []
    lines.append(f"function vector bit_{char}(scalar pos) {{")
    for p in range(25):
        lines.append(
            f"    scalar s{p:02d} = 0.0 - 1000.0 * (pos - {float(p):.1f}) * (pos - {float(p):.1f});"
        )
    scores = ", ".join(f"s{p:02d}" for p in range(25))
    vals = ", ".join(f"make_real({bits[p]:.1f})" for p in range(25))
    lines.append(f"    return select([{scores}], [{vals}]);")
    lines.append("}")
    return "\n".join(lines)


def gen_glyph_pixel() -> str:
    """36-way defuzzified select over char_code -> the per-letter bit at (x, y)."""
    lines: list[str] = []
    lines.append("function vector glyph_pixel(scalar x, scalar y, scalar char_code) {")
    lines.append("    scalar pos = y * 5.0 + x;")
    lines.append("")
    lines.append("    // Per-letter bit at this position. Each `bit_<C>(pos)` is a 25-way")
    lines.append("    // defuzzified select over the 25 grid positions of letter <C>.")
    for c in CHARS_ORDER:
        # Use a safe identifier: digits get prefixed with `d`.
        suffix = c if c.isalpha() else f"d{c}"
        lines.append(f"    vector b_{suffix} = bit_{c}(pos);")
    lines.append("")
    lines.append("    // Score char_code against each letter's codepoint. The softmax-")
    lines.append("    // saturation constant (1000) clears float64 underflow (~745), so")
    lines.append("    // exp(-1000) is exactly 0 and select is a true one-hot.")
    for c in CHARS_ORDER:
        suffix = c if c.isalpha() else f"d{c}"
        cp = ord(c)
        lines.append(
            f"    scalar s_{suffix} = 0.0 - 1000.0 * (char_code - {float(cp):.1f}) "
            f"* (char_code - {float(cp):.1f});"
        )
    lines.append("")
    scores = ", ".join(
        f"s_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    branches = ", ".join(
        f"b_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    lines.append(f"    return select([{scores}], [{branches}]);")
    lines.append("}")
    return "\n".join(lines)


def gen_step() -> str:
    """Emma's recurrent step: ``state = prev*0 + glyph_pixel(...)``."""
    return """\
function vector step(vector prev_state, scalar x, scalar y, scalar char_code) {
    // Emma's recurrent step: discard the previous pixel state (`* 0`), then
    // add the new glyph's bit at this position. The * 0 is explicit -- the
    // substrate forgets, not the host. Both summands are real-axis vectors,
    // so the sum is real-axis too (no make_real needed).
    vector zeroed = prev_state * 0.0;
    vector new_pix = glyph_pixel(x, y, char_code);
    return zeroed + new_pix;
}
"""


def generate() -> str:
    """Emit the full .su source as a string."""
    parts: list[str] = [_HEADER, ""]
    parts.append(gen_step())
    parts.append("")
    parts.append(gen_glyph_pixel())
    parts.append("")
    parts.append("// ============================================================")
    parts.append("// Per-letter bit lookups (25-way position selects), one per char.")
    parts.append("// ============================================================")
    for c in CHARS_ORDER:
        parts.append("")
        parts.append(gen_bit_function(c))
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    repo_root = pathlib.Path(__file__).resolve().parent.parent
    out = repo_root / "apps" / "font" / "font.su"
    out.parent.mkdir(parents=True, exist_ok=True)
    src = generate()
    out.write_text(src, encoding="utf-8", newline="\n")
    n_lines = src.count("\n") + 1
    print(f"[gen] wrote {out} ({n_lines} lines, "
          f"{len(FONT_5x5)} glyphs)")


if __name__ == "__main__":
    main()
