"""Generate apps/font/font.su from tools/font_data.py (Emma 2026-05-26).

The .su file is long but mechanical — 36 letter functions, each a 25-way
position select; plus an outer 36-way letter select. Hand-writing this is
both error-prone and obscures intent. Generate it from font_data.py instead,
so the font shape lives in one place (the data) and the substrate dispatch
shape lives in one place (this generator).

Re-run after editing tools/font_data.py:

    python tools/generate_font_su.py

The generator does not run on the substrate; it is build-time tooling that
emits .su source. The .su that gets shipped IS what the substrate executes.
"""
from __future__ import annotations

import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from font_data import CHARS_ORDER, FONT_5x5, bits_for


_HEADER = """\
// font.su -- GENERATED by tools/generate_font_su.py from tools/font_data.py.
// DO NOT EDIT BY HAND -- regenerate via `python tools/generate_font_su.py`.
//
// Emma's text-input demo (2026-05-26, extended 2026-05-27): each tick shows
// a character as a 5x5 pixel glyph on the substrate. By default the char_code
// auto-advances through the 36-glyph cycle (A->Z->0->9->A); a keypress
// replaces the state (the typed code "takes the place"). Substrate
// computations:
//
//   step(prev_state, x, y, char_code)
//       Emma's recurrent step for the pixel field. The current pixel value at
//       (x, y) is the state; each tick, `state = prev*0 + glyph_pixel(...)` --
//       explicit substrate "forget then add", same shape as toggle.su's flip
//       and count.su's +1. The * 0 is the substrate's way of saying "discard
//       previous state"; the +/glyph is the substrate's way of saying "the
//       new input is now what's on screen."
//
//   cycle_step(prev_code, typed_code, has_typed) -- 2026-05-27
//       Emma's recurrent step for the *character* (not the pixel). The
//       previous char_code is the state; without an override, the substrate
//       advances it one step around the 36-glyph cycle (A->B->...->Z->0->...
//       ->9->A) via a 36-way defuzzified select. With has_typed=1.0, the
//       weighted sum `has_typed*typed_code + (1-has_typed)*advanced` lets
//       the typed code take the place -- override decided on the substrate,
//       not by a host if.
//
//   glyph_pixel(x, y, char_code)
//       Returns 1.0 if pixel (x, y) is lit for the letter with this codepoint,
//       else 0.0. Decided ON THE SUBSTRATE: 36-way defuzzified `select` over
//       A-Z + 0-9, made one-hot by softmax saturation (scores
//       -1000*(char_code - target_code)^2 -> exp underflows to exact 0 in
//       float32 AND float64, so the selected branch passes through and the
//       others are zeroed by exact-zero weights -- the same one-hot trick
//       apps/calc/switch.su uses for operator dispatch).
//
//   bit_<C>(pos) (helpers, one per of the 36 chars)
//       The lit/unlit bit for character <C> at flat position pos = y*5 + x
//       (pos in 0..24). Same defuzzified-select pattern, 25-way over pos.
//
// Together: each tick -> cycle_step(prev_code, ...) gives next char_code
//                 -> for each of 25 cells, glyph_pixel(x, y, code) selects
//                    a bit from the 36-way outer + 25-way inner switches.
// No host font table on the runtime path; both the cycle advance and the
// lit/unlit decision are the substrate's. Host stays I/O: tick the clock,
// read keypresses, paint pixels.
"""


def gen_bit_function(char: str) -> str:
    """One ``bit_<C>(scalar pos)`` returning the lit/unlit bit for char at pos."""
    bits = bits_for(char)
    lines: list[str] = []
    lines.append(f"function vector bit_{char}(scalar pos) {{")
    for p in range(25):
        lines.append(
            f"    scalar s{p:02d} = 0.0 - 1000.0 * (pos - {float(p):.1f}) * (pos - {float(p):.1f});"
        )
    scores = ", ".join(f"s{p:02d}" for p in range(25))
    vals = ", ".join(f"make_real({bits[p]:.1f})" for p in range(25))
    lines.append(f"    return select([{scores}], [{vals}]);")
    lines.append("}")
    return "\n".join(lines)


def gen_glyph_pixel() -> str:
    """36-way defuzzified select over char_code -> the per-letter bit at (x, y)."""
    lines: list[str] = []
    lines.append("function vector glyph_pixel(scalar x, scalar y, scalar char_code) {")
    lines.append("    scalar pos = y * 5.0 + x;")
    lines.append("")
    lines.append("    // Per-letter bit at this position. Each `bit_<C>(pos)` is a 25-way")
    lines.append("    // defuzzified select over the 25 grid positions of letter <C>.")
    for c in CHARS_ORDER:
        # Use a safe identifier: digits get prefixed with `d`.
        suffix = c if c.isalpha() else f"d{c}"
        lines.append(f"    vector b_{suffix} = bit_{c}(pos);")
    lines.append("")
    lines.append("    // Score char_code against each letter's codepoint. The softmax-")
    lines.append("    // saturation constant (1000) clears float64 underflow (~745), so")
    lines.append("    // exp(-1000) is exactly 0 and select is a true one-hot.")
    for c in CHARS_ORDER:
        suffix = c if c.isalpha() else f"d{c}"
        cp = ord(c)
        lines.append(
            f"    scalar s_{suffix} = 0.0 - 1000.0 * (char_code - {float(cp):.1f}) "
            f"* (char_code - {float(cp):.1f});"
        )
    lines.append("")
    scores = ", ".join(
        f"s_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    branches = ", ".join(
        f"b_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    lines.append(f"    return select([{scores}], [{branches}]);")
    lines.append("}")
    return "\n".join(lines)


def gen_step() -> str:
    """Emma's recurrent step: ``state = prev*0 + glyph_pixel(...)``."""
    return """\
function vector step(vector prev_state, scalar x, scalar y, scalar char_code) {
    // Emma's recurrent step: discard the previous pixel state (`* 0`), then
    // add the new glyph's bit at this position. The * 0 is explicit -- the
    // substrate forgets, not the host. Both summands are real-axis vectors,
    // so the sum is real-axis too (no make_real needed).
    vector zeroed = prev_state * 0.0;
    vector new_pix = glyph_pixel(x, y, char_code);
    return zeroed + new_pix;
}
"""


def gen_cycle_step() -> str:
    """Emma's recurrent step on the *character code* (added 2026-05-27).

    Without a keypress, the char_code advances one step around the 36-glyph
    cycle (A->B->...->Z->0->...->9->A) via a 36-way defuzzified select that
    enumerates every (prev_code -> next_code) pair. With ``has_typed=1.0``
    the substrate weighted sum lets the typed code take the place of the
    advanced one. No host ``if`` -- the override is just arithmetic on the
    real axis, the same way ``step`` does ``prev*0 + glyph_pixel(...)``.
    """
    # Cycle order: A..Z then 0..9, wrapping back to A.
    cycle = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    pairs: list[tuple[int, int]] = []
    for i, c in enumerate(cycle):
        nxt = cycle[(i + 1) % len(cycle)]
        pairs.append((ord(c), ord(nxt)))

    lines: list[str] = []
    lines.append("function vector cycle_step(scalar prev_code, scalar typed_code, scalar has_typed) {")
    lines.append("    // 36-way defuzzified select: for each supported prev_code, the next code")
    lines.append("    // in cycle order (A->B, ..., Y->Z, Z->0, 0->1, ..., 8->9, 9->A). Same")
    lines.append("    // softmax-saturation trick as glyph_pixel -- exp(-1000) underflows in")
    lines.append("    // float64, so the matching score's branch passes through and the others")
    lines.append("    // are zeroed.")
    for cp, _ in pairs:
        lines.append(
            f"    scalar s_{cp} = 0.0 - 1000.0 * (prev_code - {float(cp):.1f}) "
            f"* (prev_code - {float(cp):.1f});"
        )
    lines.append("")
    scores = ", ".join(f"s_{cp}" for cp, _ in pairs)
    branches = ", ".join(f"make_real({float(nxt):.1f})" for _, nxt in pairs)
    lines.append("    // advanced_vec is make_real(next_code) for the matching prev_code.")
    lines.append(f"    vector advanced_vec = select([{scores}], [{branches}]);")
    lines.append("")
    lines.append("    // Override: if has_typed=1.0, the typed code replaces the advance;")
    lines.append("    // if has_typed=0.0, the advance passes through. Substrate weighted sum,")
    lines.append("    // not a host if -- both branches are computed; the gate picks.")
    lines.append("    vector typed_vec = make_real(typed_code);")
    lines.append("    return advanced_vec * (1.0 - has_typed) + typed_vec * has_typed;")
    lines.append("}")
    return "\n".join(lines)


def generate() -> str:
    """Emit the full .su source as a string."""
    parts: list[str] = [_HEADER, ""]
    parts.append(gen_step())
    parts.append("")
    parts.append(gen_cycle_step())
    parts.append("")
    parts.append(gen_glyph_pixel())
    parts.append("")
    parts.append("// ============================================================")
    parts.append("// Per-letter bit lookups (25-way position selects), one per char.")
    parts.append("// ============================================================")
    for c in CHARS_ORDER:
        parts.append("")
        parts.append(gen_bit_function(c))
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    repo_root = pathlib.Path(__file__).resolve().parent.parent
    out = repo_root / "apps" / "font" / "font.su"
    out.parent.mkdir(parents=True, exist_ok=True)
    src = generate()
    out.write_text(src, encoding="utf-8", newline="\n")
    n_lines = src.count("\n") + 1
    print(f"[gen] wrote {out} ({n_lines} lines, "
          f"{len(FONT_5x5)} glyphs)")


if __name__ == "__main__":
    main()
