"""Generate apps/font/font_bound.su from tools/font_data.py.

Bound-vector implementation of the font demo per planning/26-font-bound-vector-
rewrite.md. The existing tools/generate_font_su.py emits a 36-way x 25-way
defuzzified-select tree (~22500 substrate branches per keypress); this
generator emits the rotation-binding pattern instead:

  - 25 position basis vectors (p_00..p_24) — one rotation role per (x, y) cell.
  - LIT / UNLIT basis vectors — fillers.
  - 36 per-character glyph bundles, each a bundle of 25 (position |-> LIT or
    UNLIT) bindings.
  - glyph_pixel_bound(x, y, char_code) — 36-way outer select picks the right
    glyph bundle by char_code, 25-way inner select picks the right pos basis
    by (x, y), then unbind(pos, glyph) -> bit_vec; return make_real(
    similarity(bit_vec, LIT)).

The substrate output is fuzzy (a cosine similarity in roughly [0, 1] with
rotation-binding noise from the 25 bound items per glyph). The host clips
to {0, 1} for display. Existing tests/test_font.py uses 1e-9 tolerance and
WILL NOT pass against this output — that's expected, the rewrite is fuzzy
by design and gets its own measured-capacity test (test_font_bound.py).

Re-run after editing tools/font_data.py:

    python tools/generate_font_bound_su.py
"""
from __future__ import annotations

import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from font_data import CHARS_ORDER, bits_for  # noqa: E402


_HEADER = """\
// font_bound.su -- GENERATED by tools/generate_font_bound_su.py.
// DO NOT EDIT BY HAND -- regenerate via `python tools/generate_font_bound_su.py`.
//
// Bound-vector rewrite of font.su per planning/26-font-bound-vector-rewrite.md.
// Each character is a single bundle of 25 (position -> lit/unlit) rotation-
// bindings; the glyph_pixel lookup unbinds the position from the glyph and
// returns the cosine similarity to LIT on the real axis.
//
// Per keypress this dispatches ~25 cells * (36-way outer select + 25-way pos
// select + 1 unbind + 1 similarity) ~= 1600 substrate ops, vs ~22500 in
// the original font.su (25-way inner switch per character). The bottleneck
// on this runtime is Python -> torch dispatch overhead, so fewer ops -> faster
// wall clock even when the per-op tensor work is identical.
//
// Trade-off: substrate output is FUZZY (rotation-binding noise from the 25
// bound items per glyph). Cosine to LIT is ~1.0 for lit cells, ~0.0 for unlit,
// with capacity-dependent crosstalk. The host displays the field clipped to
// [0, 1]. Existing tests/test_font.py uses 1e-9 tolerance and will NOT pass
// against this output -- that's expected; this gets its own measured-tolerance
// test in tests/test_font_bound.py.
"""


def _basis_decl(name: str) -> str:
    return f'vector {name} = basis_vector("font_bound_{name}");'


def gen_basis_block() -> str:
    """Position basis (25) + LIT + UNLIT + per-character basis (36)."""
    lines: list[str] = []
    lines.append("// --- Basis vectors (codebook entries; embedded once at module load) ---")
    lines.append("// 25 position basis vectors, one rotation role per (x, y) cell of the 5x5 grid.")
    for pos in range(25):
        lines.append(_basis_decl(f"p_{pos:02d}"))
    lines.append("")
    lines.append("// Fillers: LIT marker for a lit pixel, UNLIT for an unlit pixel.")
    lines.append(_basis_decl("LIT"))
    lines.append(_basis_decl("UNLIT"))
    lines.append("")
    lines.append("// 36 per-character basis vectors -- not strictly needed for glyph lookup")
    lines.append("// (we select glyphs by char_code via defuzzified select), but kept here as")
    lines.append("// codebook entries the host can build a char-string from if needed downstream.")
    for c in CHARS_ORDER:
        suffix = c if c.isalpha() else f"d{c}"
        lines.append(_basis_decl(f"c_{suffix}"))
    return "\n".join(lines)


def gen_glyph_bundles() -> str:
    """36 bundles, one per char: bundle(bind(p_NN, LIT or UNLIT) for each cell)."""
    lines: list[str] = []
    lines.append("// --- Per-character glyph bundles (rotation-bindings) ---")
    lines.append("// Each glyph_X is one substrate vector encoding the 25 lit/unlit bits via")
    lines.append("// 25 (position -> LIT/UNLIT) bindings. The bundle's rotation-binding capacity")
    lines.append("// at N=25 bindings in a small runtime_dim is what determines the noise floor;")
    lines.append("// the measured-tolerance test reports the actual cosine gap.")
    for c in CHARS_ORDER:
        suffix = c if c.isalpha() else f"d{c}"
        bits = bits_for(c)  # 25 floats in row-major (y*5+x)
        lines.append("")
        lines.append(f"vector glyph_{suffix} = bundle(")
        binds = []
        for pos in range(25):
            marker = "LIT" if bits[pos] > 0.5 else "UNLIT"
            binds.append(f"    bind(p_{pos:02d}, {marker})")
        lines.append(",\n".join(binds))
        lines.append(");")
    return "\n".join(lines)


def gen_glyph_pixel_bound() -> str:
    """The runtime function: 36-way outer + 25-way pos + unbind + similarity."""
    lines: list[str] = []
    lines.append("function vector glyph_pixel_bound(scalar x, scalar y, scalar char_code) {")
    lines.append("    scalar pos = y * 5.0 + x;")
    lines.append("")
    lines.append("    // 36-way defuzzified outer select picks the right glyph bundle by char_code.")
    lines.append("    // Same softmax-saturation pattern as the existing font.su glyph_pixel:")
    lines.append("    // exp(-1000 * delta^2) underflows in float64, making the matching score's")
    lines.append("    // branch one-hot.")
    for c in CHARS_ORDER:
        suffix = c if c.isalpha() else f"d{c}"
        cp = ord(c)
        lines.append(
            f"    scalar sc_{suffix} = 0.0 - 1000.0 * (char_code - {float(cp):.1f})"
            f" * (char_code - {float(cp):.1f});"
        )
    lines.append("")
    score_list = ", ".join(
        f"sc_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    glyph_list = ", ".join(
        f"glyph_{c if c.isalpha() else f'd{c}'}" for c in CHARS_ORDER
    )
    lines.append(f"    vector glyph = select([{score_list}], [{glyph_list}]);")
    lines.append("")
    lines.append("    // 25-way defuzzified select picks the matching position basis vector for pos.")
    for p in range(25):
        lines.append(
            f"    scalar sp_{p:02d} = 0.0 - 1000.0 * (pos - {float(p):.1f})"
            f" * (pos - {float(p):.1f});"
        )
    lines.append("")
    pos_scores = ", ".join(f"sp_{p:02d}" for p in range(25))
    pos_basis = ", ".join(f"p_{p:02d}" for p in range(25))
    lines.append(f"    vector pos_vec = select([{pos_scores}], [{pos_basis}]);")
    lines.append("")
    lines.append("    // Unbind position from glyph -> a noisy approximation of LIT or UNLIT.")
    lines.append("    // Similarity to LIT -> ~1 lit, ~0 unlit. Lifted to real-axis vector.")
    lines.append("    vector bit_vec = unbind(pos_vec, glyph);")
    lines.append("    return make_real(similarity(bit_vec, LIT));")
    lines.append("}")
    lines.append("")
    lines.append("function vector main() { return glyph_pixel_bound(2.0, 0.0, 65.0); }")
    return "\n".join(lines)


def generate() -> str:
    parts: list[str] = [_HEADER, ""]
    parts.append(gen_basis_block())
    parts.append("")
    parts.append(gen_glyph_bundles())
    parts.append("")
    parts.append(gen_glyph_pixel_bound())
    parts.append("")
    return "\n".join(parts)


def main() -> None:
    repo_root = pathlib.Path(__file__).resolve().parent.parent
    out = repo_root / "apps" / "font" / "font_bound.su"
    out.parent.mkdir(parents=True, exist_ok=True)
    src = generate()
    out.write_text(src, encoding="utf-8", newline="\n")
    n_lines = src.count("\n") + 1
    print(f"[gen-bound] wrote {out} ({n_lines} lines)")


if __name__ == "__main__":
    main()
